/**
 * @file article_praise_rel_info.h
 * @brief 文章点赞关联表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#pragma once

#include <vector>

#include <chen/db/db.h>
#include <chen/db/query_builder.h>
#include <chen/util/util.h>

namespace blog {
namespace data {

class ArticlePraiseRelInfoDao;
/**
 * @brief 文章点赞关联表
 */
class ArticlePraiseRelInfo {
friend class ArticlePraiseRelInfoDao;
public:
    typedef std::shared_ptr<ArticlePraiseRelInfo> ptr;

    ArticlePraiseRelInfo();

    /**
     * @brief 获取主键ID
     * @return 主键ID
     */
    const int64_t& getId() { return m_id; }
    /**
     * @brief 设置主键ID
     * @param v 主键ID
     */
    void setId(const int64_t& v);

    /**
     * @brief 获取点赞用户ID
     * @return 点赞用户ID
     */
    const int64_t& getUserId() { return m_userId; }
    /**
     * @brief 设置点赞用户ID
     * @param v 点赞用户ID
     */
    void setUserId(const int64_t& v);

    /**
     * @brief 获取文章ID
     * @return 文章ID
     */
    const int64_t& getArticleId() { return m_articleId; }
    /**
     * @brief 设置文章ID
     * @param v 文章ID
     */
    void setArticleId(const int64_t& v);

    /**
     * @brief 获取是否删除
     * @return 是否删除
     */
    const int32_t& getIsDeleted() { return m_isDeleted; }
    /**
     * @brief 设置是否删除
     * @param v 是否删除
     */
    void setIsDeleted(const int32_t& v);

    /**
     * @brief 获取创建时间
     * @return 创建时间
     */
    const int64_t& getCreateTime() { return m_createTime; }
    /**
     * @brief 设置创建时间
     * @param v 创建时间
     */
    void setCreateTime(const int64_t& v);

    /**
     * @brief 获取更新时间
     * @return 更新时间
     */
    const int64_t& getUpdateTime() { return m_updateTime; }
    /**
     * @brief 设置更新时间
     * @param v 更新时间
     */
    void setUpdateTime(const int64_t& v);

    /**
     * @brief 转为 JSON 字符串
     * @return JSON 字符串
     */
    std::string toJsonString() const;

    /** @brief 清除脏标记（Update 成功后自动调用） */
    void markClean() { m_flags = 0; }
    /**
     * @brief 是否有字段被修改过
     * @return true 有未保存的修改，false 无修改
     */
    bool isDirty() const { return m_flags != 0; }

private:
    int32_t m_isDeleted;
    int64_t m_id;
    int64_t m_userId;
    int64_t m_articleId;
    int64_t m_createTime;
    int64_t m_updateTime;
    uint64_t m_flags = 0;
};


class ArticlePraiseRelInfoDao {
public:
    typedef std::shared_ptr<ArticlePraiseRelInfoDao> ptr;
    static int Update(ArticlePraiseRelInfo::ptr info, chen::IDB::ptr conn);
    static int Insert(ArticlePraiseRelInfo::ptr info, chen::IDB::ptr conn);
    static int InsertOrUpdate(ArticlePraiseRelInfo::ptr info, chen::IDB::ptr conn);
    static int BatchInsert(const std::vector<ArticlePraiseRelInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchUpdate(const std::vector<ArticlePraiseRelInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchDelete(const std::vector<int64_t>& ids, chen::IDB::ptr conn);
    static int Delete(ArticlePraiseRelInfo::ptr info, chen::IDB::ptr conn);
    static int Delete(const int64_t& id, chen::IDB::ptr conn);
    static int DeleteById( const int64_t& id, chen::IDB::ptr conn);
    static int DeleteByUserIdArticleId( const int64_t& user_id,  const int64_t& article_id, chen::IDB::ptr conn);
    static int DeleteByUserId( const int64_t& user_id, chen::IDB::ptr conn);
    static int DeleteByArticleId( const int64_t& article_id, chen::IDB::ptr conn);
    static int QueryAll(std::vector<ArticlePraiseRelInfo::ptr>& results, chen::IDB::ptr conn);
    static ArticlePraiseRelInfo::ptr Query( const int64_t& id, chen::IDB::ptr conn);
    static ArticlePraiseRelInfo::ptr QueryByUserIdArticleId( const int64_t& user_id,  const int64_t& article_id, chen::IDB::ptr conn);
    static int QueryByUserId(std::vector<ArticlePraiseRelInfo::ptr>& results,  const int64_t& user_id, chen::IDB::ptr conn);
    static int QueryByUserIdPages(std::vector<ArticlePraiseRelInfo::ptr>& results, int64_t& total,  const int64_t& user_id, int32_t offset, int32_t limit, chen::IDB::ptr conn);
    static int QueryByArticleId(std::vector<ArticlePraiseRelInfo::ptr>& results,  const int64_t& article_id, chen::IDB::ptr conn);
    static int QueryByArticleIdPages(std::vector<ArticlePraiseRelInfo::ptr>& results, int64_t& total,  const int64_t& article_id, int32_t offset, int32_t limit, chen::IDB::ptr conn);
    static int CreateTableSQLite3(chen::IDB::ptr info);
    static int CreateTableMySQL(chen::IDB::ptr info);
    static int MigrateTableSQLite3(chen::IDB::ptr info);
    static int MigrateTableMySQL(chen::IDB::ptr info);
    static int Migrate(chen::IDB::ptr conn);
    static ArticlePraiseRelInfo::ptr ParseRow(chen::ISQLData::ptr data);
    static int QueryByBuilder(std::vector<ArticlePraiseRelInfo::ptr>& results, chen::QueryBuilder::ptr qb, chen::IDB::ptr conn);
    static int QueryByBuilderPages(std::vector<ArticlePraiseRelInfo::ptr>& results, int64_t& total, chen::QueryBuilder::ptr qb, int32_t offset, int32_t limit, chen::IDB::ptr conn);
};

} //namespace data
} //namespace blog
