/**
 * @file assignment_organization_rel_info.cc
 * @brief 作业-组织关联表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#include "assignment_organization_rel_info.h"

#include <chen/log/log.h>

#include <map>

namespace blog {
namespace data {

static chen::Logger::ptr logger = LOG_NAME("orm");

AssignmentOrganizationRelInfo::AssignmentOrganizationRelInfo()
    :m_status(1)
    ,m_isDeleted(0)
    ,m_id()
    ,m_assignmentId()
    ,m_organizationId()
    ,m_assignedBy()
    ,m_createTime(time(0))
    ,m_updateTime() {
}

std::string AssignmentOrganizationRelInfo::toJsonString() const {
    Json::Value v;
    v["id"] = std::to_string(m_id);
    v["assignment_id"] = std::to_string(m_assignmentId);
    v["organization_id"] = std::to_string(m_organizationId);
    v["assigned_by"] = m_assignedBy;
    v["status"] = m_status;
    v["is_deleted"] = m_isDeleted;
    v["create_time"] = chen::Time2Str(m_createTime);
    v["update_time"] = chen::Time2Str(m_updateTime);
    return chen::JsonUtil::ToString(v);
}

void AssignmentOrganizationRelInfo::setId(const int64_t& v) {
    m_id = v;
}

void AssignmentOrganizationRelInfo::setAssignmentId(const int64_t& v) {
    m_assignmentId = v;
}

void AssignmentOrganizationRelInfo::setOrganizationId(const int64_t& v) {
    m_organizationId = v;
}

void AssignmentOrganizationRelInfo::setAssignedBy(const std::string& v) {
    m_assignedBy = v;
}

void AssignmentOrganizationRelInfo::setStatus(const int32_t& v) {
    m_status = v;
}

void AssignmentOrganizationRelInfo::setIsDeleted(const int32_t& v) {
    m_isDeleted = v;
}

void AssignmentOrganizationRelInfo::setCreateTime(const int64_t& v) {
    m_createTime = v;
}

void AssignmentOrganizationRelInfo::setUpdateTime(const int64_t& v) {
    m_updateTime = v;
}


int AssignmentOrganizationRelInfoDao::Update(AssignmentOrganizationRelInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "update assignment_organization_rel set assignment_id = ?, organization_id = ?, assigned_by = ?, status = ?, is_deleted = ?, create_time = ?, update_time = ? where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_assignmentId);
    stmt->bindInt64(2, info->m_organizationId);
    stmt->bindString(3, info->m_assignedBy);
    stmt->bindInt32(4, info->m_status);
    stmt->bindInt32(5, info->m_isDeleted);
    stmt->bindTime(6, info->m_createTime);
    stmt->bindTime(7, info->m_updateTime);
    stmt->bindInt64(8, info->m_id);
    return stmt->execute();
}

int AssignmentOrganizationRelInfoDao::Insert(AssignmentOrganizationRelInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "insert into assignment_organization_rel (assignment_id, organization_id, assigned_by, status, is_deleted, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_assignmentId);
    stmt->bindInt64(2, info->m_organizationId);
    stmt->bindString(3, info->m_assignedBy);
    stmt->bindInt32(4, info->m_status);
    stmt->bindInt32(5, info->m_isDeleted);
    stmt->bindTime(6, info->m_createTime);
    stmt->bindTime(7, info->m_updateTime);
    int rt = stmt->execute();
    if(rt == 0) {
        info->m_id = conn->getLastInsertId();
    }
    return rt;
}

int AssignmentOrganizationRelInfoDao::InsertOrUpdate(AssignmentOrganizationRelInfo::ptr info, chen::IDB::ptr conn) {
    if(info->m_id == 0) {
        return Insert(info, conn);
    }
    std::string sql = "replace into assignment_organization_rel (id, assignment_id, organization_id, assigned_by, status, is_deleted, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    stmt->bindInt64(2, info->m_assignmentId);
    stmt->bindInt64(3, info->m_organizationId);
    stmt->bindString(4, info->m_assignedBy);
    stmt->bindInt32(5, info->m_status);
    stmt->bindInt32(6, info->m_isDeleted);
    stmt->bindTime(7, info->m_createTime);
    stmt->bindTime(8, info->m_updateTime);
    return stmt->execute();
}

int AssignmentOrganizationRelInfoDao::Delete(AssignmentOrganizationRelInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "delete from assignment_organization_rel where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    return stmt->execute();
}

int AssignmentOrganizationRelInfoDao::DeleteById( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "delete from assignment_organization_rel where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, id);
    return stmt->execute();
}

int AssignmentOrganizationRelInfoDao::DeleteByAssignmentIdOrganizationId( const int64_t& assignment_id,  const int64_t& organization_id, chen::IDB::ptr conn) {
    std::string sql = "delete from assignment_organization_rel where assignment_id = ? and organization_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, assignment_id);
    stmt->bindInt64(1, organization_id);
    return stmt->execute();
}

int AssignmentOrganizationRelInfoDao::DeleteByAssignmentId( const int64_t& assignment_id, chen::IDB::ptr conn) {
    std::string sql = "delete from assignment_organization_rel where assignment_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, assignment_id);
    return stmt->execute();
}

int AssignmentOrganizationRelInfoDao::DeleteByOrganizationId( const int64_t& organization_id, chen::IDB::ptr conn) {
    std::string sql = "delete from assignment_organization_rel where organization_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, organization_id);
    return stmt->execute();
}

int AssignmentOrganizationRelInfoDao::QueryAll(std::vector<AssignmentOrganizationRelInfo::ptr>& results, chen::IDB::ptr conn) {
    std::string sql = "select id, assignment_id, organization_id, assigned_by, status, is_deleted, create_time, update_time from assignment_organization_rel";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    auto rt = stmt->query();
    if(!rt) {
        return stmt->getErrno();
    }
    while (rt->next()) {
        AssignmentOrganizationRelInfo::ptr v(new AssignmentOrganizationRelInfo);
        v->m_id = rt->getInt64(0);
        v->m_assignmentId = rt->getInt64(1);
        v->m_organizationId = rt->getInt64(2);
        v->m_assignedBy = rt->getString(3);
        v->m_status = rt->getInt32(4);
        v->m_isDeleted = rt->getInt32(5);
        v->m_createTime = rt->getTime(6);
        v->m_updateTime = rt->getTime(7);
        results.push_back(v);
    }
    return 0;
}

AssignmentOrganizationRelInfo::ptr AssignmentOrganizationRelInfoDao::Query( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "select id, assignment_id, organization_id, assigned_by, status, is_deleted, create_time, update_time from assignment_organization_rel where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindInt64(1, id);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    AssignmentOrganizationRelInfo::ptr v(new AssignmentOrganizationRelInfo);
    v->m_id = rt->getInt64(0);
    v->m_assignmentId = rt->getInt64(1);
    v->m_organizationId = rt->getInt64(2);
    v->m_assignedBy = rt->getString(3);
    v->m_status = rt->getInt32(4);
    v->m_isDeleted = rt->getInt32(5);
    v->m_createTime = rt->getTime(6);
    v->m_updateTime = rt->getTime(7);
    return v;
}

AssignmentOrganizationRelInfo::ptr AssignmentOrganizationRelInfoDao::QueryByAssignmentIdOrganizationId( const int64_t& assignment_id,  const int64_t& organization_id, chen::IDB::ptr conn) {
    std::string sql = "select id, assignment_id, organization_id, assigned_by, status, is_deleted, create_time, update_time from assignment_organization_rel where assignment_id = ? and organization_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindInt64(1, assignment_id);
    stmt->bindInt64(2, organization_id);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    AssignmentOrganizationRelInfo::ptr v(new AssignmentOrganizationRelInfo);
    v->m_id = rt->getInt64(0);
    v->m_assignmentId = rt->getInt64(1);
    v->m_organizationId = rt->getInt64(2);
    v->m_assignedBy = rt->getString(3);
    v->m_status = rt->getInt32(4);
    v->m_isDeleted = rt->getInt32(5);
    v->m_createTime = rt->getTime(6);
    v->m_updateTime = rt->getTime(7);
    return v;
}

int AssignmentOrganizationRelInfoDao::QueryByAssignmentId(std::vector<AssignmentOrganizationRelInfo::ptr>& results,  const int64_t& assignment_id, chen::IDB::ptr conn) {
    std::string sql = "select id, assignment_id, organization_id, assigned_by, status, is_deleted, create_time, update_time from assignment_organization_rel where assignment_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, assignment_id);
    auto rt = stmt->query();
    if(!rt) {
        return 0;
    }
    while (rt->next()) {
        AssignmentOrganizationRelInfo::ptr v(new AssignmentOrganizationRelInfo);
        v->m_id = rt->getInt64(0);
        v->m_assignmentId = rt->getInt64(1);
        v->m_organizationId = rt->getInt64(2);
        v->m_assignedBy = rt->getString(3);
        v->m_status = rt->getInt32(4);
        v->m_isDeleted = rt->getInt32(5);
        v->m_createTime = rt->getTime(6);
        v->m_updateTime = rt->getTime(7);
        results.push_back(v);
    };
    return 0;
}

int AssignmentOrganizationRelInfoDao::QueryByAssignmentIdPages(std::vector<AssignmentOrganizationRelInfo::ptr>& results, int64_t& total,  const int64_t& assignment_id, int32_t offset, int32_t limit, chen::IDB::ptr conn) {
    std::string countSql = "select count(*) from assignment_organization_rel where assignment_id = ?";
    auto countStmt = conn->prepare(countSql);
    if (!countStmt) {
        ERROR(logger) << "stmt=" << countSql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    countStmt->bindInt64(1, assignment_id);
    auto countRt = countStmt->query();
    if (!countRt) {
        return countStmt->getErrno();
    }
    if (countRt->next()) {
        total = countRt->getInt64(0);
    }
    if (total == 0) {
        return 0;
    }
    std::string sql = "select id, assignment_id, organization_id, assigned_by, status, is_deleted, create_time, update_time from assignment_organization_rel where assignment_id = ? order by id desc limit ? offset ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, assignment_id);
    stmt->bindInt32(2, limit);
    stmt->bindInt32(3, offset);
    auto rt = stmt->query();
    if (!rt) {
        return 0;
    }
    while (rt->next()) {
        AssignmentOrganizationRelInfo::ptr v(new AssignmentOrganizationRelInfo);
        v->m_id = rt->getInt64(0);
        v->m_assignmentId = rt->getInt64(1);
        v->m_organizationId = rt->getInt64(2);
        v->m_assignedBy = rt->getString(3);
        v->m_status = rt->getInt32(4);
        v->m_isDeleted = rt->getInt32(5);
        v->m_createTime = rt->getTime(6);
        v->m_updateTime = rt->getTime(7);
        results.push_back(v);
    };
    return 0;
}

int AssignmentOrganizationRelInfoDao::QueryByOrganizationId(std::vector<AssignmentOrganizationRelInfo::ptr>& results,  const int64_t& organization_id, chen::IDB::ptr conn) {
    std::string sql = "select id, assignment_id, organization_id, assigned_by, status, is_deleted, create_time, update_time from assignment_organization_rel where organization_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, organization_id);
    auto rt = stmt->query();
    if(!rt) {
        return 0;
    }
    while (rt->next()) {
        AssignmentOrganizationRelInfo::ptr v(new AssignmentOrganizationRelInfo);
        v->m_id = rt->getInt64(0);
        v->m_assignmentId = rt->getInt64(1);
        v->m_organizationId = rt->getInt64(2);
        v->m_assignedBy = rt->getString(3);
        v->m_status = rt->getInt32(4);
        v->m_isDeleted = rt->getInt32(5);
        v->m_createTime = rt->getTime(6);
        v->m_updateTime = rt->getTime(7);
        results.push_back(v);
    };
    return 0;
}

int AssignmentOrganizationRelInfoDao::QueryByOrganizationIdPages(std::vector<AssignmentOrganizationRelInfo::ptr>& results, int64_t& total,  const int64_t& organization_id, int32_t offset, int32_t limit, chen::IDB::ptr conn) {
    std::string countSql = "select count(*) from assignment_organization_rel where organization_id = ?";
    auto countStmt = conn->prepare(countSql);
    if (!countStmt) {
        ERROR(logger) << "stmt=" << countSql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    countStmt->bindInt64(1, organization_id);
    auto countRt = countStmt->query();
    if (!countRt) {
        return countStmt->getErrno();
    }
    if (countRt->next()) {
        total = countRt->getInt64(0);
    }
    if (total == 0) {
        return 0;
    }
    std::string sql = "select id, assignment_id, organization_id, assigned_by, status, is_deleted, create_time, update_time from assignment_organization_rel where organization_id = ? order by id desc limit ? offset ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, organization_id);
    stmt->bindInt32(2, limit);
    stmt->bindInt32(3, offset);
    auto rt = stmt->query();
    if (!rt) {
        return 0;
    }
    while (rt->next()) {
        AssignmentOrganizationRelInfo::ptr v(new AssignmentOrganizationRelInfo);
        v->m_id = rt->getInt64(0);
        v->m_assignmentId = rt->getInt64(1);
        v->m_organizationId = rt->getInt64(2);
        v->m_assignedBy = rt->getString(3);
        v->m_status = rt->getInt32(4);
        v->m_isDeleted = rt->getInt32(5);
        v->m_createTime = rt->getTime(6);
        v->m_updateTime = rt->getTime(7);
        results.push_back(v);
    };
    return 0;
}

int AssignmentOrganizationRelInfoDao::CreateTableSQLite3(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS assignment_organization_rel("
            "id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "assignment_id INTEGER NOT NULL DEFAULT 0,"
            "organization_id INTEGER NOT NULL DEFAULT 0,"
            "assigned_by TEXT NOT NULL DEFAULT '',"
            "status INTEGER NOT NULL DEFAULT 1,"
            "is_deleted INTEGER NOT NULL DEFAULT 0,"
            "create_time TIMESTAMP NOT NULL DEFAULT current_timestamp,"
            "update_time TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00');"
            "CREATE UNIQUE INDEX IF NOT EXISTS assignment_organization_rel_assignment_id_organization_id ON assignment_organization_rel(assignment_id,organization_id);"
            "CREATE INDEX IF NOT EXISTS assignment_organization_rel_assignment_id ON assignment_organization_rel(assignment_id);"
            "CREATE INDEX IF NOT EXISTS assignment_organization_rel_organization_id ON assignment_organization_rel(organization_id);"
            );
}

int AssignmentOrganizationRelInfoDao::CreateTableMySQL(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS assignment_organization_rel("
            "`id` bigint AUTO_INCREMENT COMMENT '主键ID',"
            "`assignment_id` bigint NOT NULL DEFAULT 0 COMMENT '作业ID',"
            "`organization_id` bigint NOT NULL DEFAULT 0 COMMENT '组织ID',"
            "`assigned_by` varchar(128) NOT NULL DEFAULT '' COMMENT '负责人',"
            "`status` int NOT NULL DEFAULT 1 COMMENT '状态: 1分配 2取消',"
            "`is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除',"
            "`create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间',"
            "`update_time` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' ON UPDATE current_timestamp  COMMENT '更新时间',"
            "PRIMARY KEY(`id`),"
            "UNIQUE KEY `assignment_organization_rel_assignment_id_organization_id` (`assignment_id`,`organization_id`),"
            "KEY `assignment_organization_rel_assignment_id` (`assignment_id`),"
            "KEY `assignment_organization_rel_organization_id` (`organization_id`)) COMMENT='作业-组织关联表'");
}

int AssignmentOrganizationRelInfoDao::MigrateTableSQLite3(chen::IDB::ptr conn) {
    auto data = conn->query("PRAGMA table_info(assignment_organization_rel)");
    if (!data) {
        ERROR(logger) << "PRAGMA table_info(assignment_organization_rel) errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(1)] = data->getString(2);
    }

    bool need_recreate = false;
    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: assignment_organization_rel.id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("assignment_id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: assignment_organization_rel.assignment_id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("organization_id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: assignment_organization_rel.organization_id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("assigned_by");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: assignment_organization_rel.assigned_by " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("status");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: assignment_organization_rel.status " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("is_deleted");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: assignment_organization_rel.is_deleted " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("create_time");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: assignment_organization_rel.create_time " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("update_time");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: assignment_organization_rel.update_time " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    if (!need_recreate) {
        for (auto& [name, _] : existing_cols) {
            (void)_;  // suppress unused warning
            bool found = false;
            if (name == "id") found = true;
            if (name == "assignment_id") found = true;
            if (name == "organization_id") found = true;
            if (name == "assigned_by") found = true;
            if (name == "status") found = true;
            if (name == "is_deleted") found = true;
            if (name == "create_time") found = true;
            if (name == "update_time") found = true;
            if (!found) {
                need_recreate = true;
                WARN(logger) << "Column assignment_organization_rel." << name << " removed, table recreate required";
                break;
            }
        }
    }

    if (need_recreate) {
        INFO(logger) << "Recreating table assignment_organization_rel";

        std::vector<std::string> common_cols;
        if (existing_cols.find("id") != existing_cols.end()) {
            common_cols.push_back("id");
        }
        if (existing_cols.find("assignment_id") != existing_cols.end()) {
            common_cols.push_back("assignment_id");
        }
        if (existing_cols.find("organization_id") != existing_cols.end()) {
            common_cols.push_back("organization_id");
        }
        if (existing_cols.find("assigned_by") != existing_cols.end()) {
            common_cols.push_back("assigned_by");
        }
        if (existing_cols.find("status") != existing_cols.end()) {
            common_cols.push_back("status");
        }
        if (existing_cols.find("is_deleted") != existing_cols.end()) {
            common_cols.push_back("is_deleted");
        }
        if (existing_cols.find("create_time") != existing_cols.end()) {
            common_cols.push_back("create_time");
        }
        if (existing_cols.find("update_time") != existing_cols.end()) {
            common_cols.push_back("update_time");
        }

        if (conn->execute("ALTER TABLE assignment_organization_rel RENAME TO assignment_organization_rel_tmp")) {
            ERROR(logger) << "RENAME TABLE assignment_organization_rel failed";
            return conn->getErrno();
        }
        CreateTableSQLite3(conn);
        if (!common_cols.empty()) {
            std::string cols;
            for (size_t i = 0; i < common_cols.size(); ++i) {
                if (i) cols += ",";
                cols += common_cols[i];
            }
            std::string sql = "INSERT INTO assignment_organization_rel (" + cols + ") SELECT " + cols + " FROM assignment_organization_rel_tmp";
            if (int rt = conn->execute(sql)) {
                ERROR(logger) << "copy data from assignment_organization_rel_tmp to assignment_organization_rel failed, errno=" << rt;
                // don't return; try to continue
            }
        }
        conn->execute("DROP TABLE assignment_organization_rel_tmp");
        return 0;
    }

    if (existing_cols.find("assignment_id") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.assignment_id";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN assignment_id INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN assignment_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("organization_id") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.organization_id";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN organization_id INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN organization_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("assigned_by") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.assigned_by";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN assigned_by TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN assigned_by failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("status") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.status";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN status INTEGER NOT NULL DEFAULT 1");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("is_deleted") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.is_deleted";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN is_deleted failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("create_time") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.create_time";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN create_time TIMESTAMP NOT NULL DEFAULT current_timestamp");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("update_time") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.update_time";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN update_time TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}

int AssignmentOrganizationRelInfoDao::MigrateTableMySQL(chen::IDB::ptr conn) {
    auto data = conn->query("SHOW COLUMNS FROM assignment_organization_rel");
    if (!data) {
        ERROR(logger) << "SHOW COLUMNS FROM assignment_organization_rel errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(0)] = data->getString(1);
    }

    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column assignment_organization_rel.id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE assignment_organization_rel MODIFY COLUMN `id` bigint NOT NULL DEFAULT 0 COMMENT '主键ID'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN assignment_organization_rel.id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("assignment_id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column assignment_organization_rel.assignment_id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE assignment_organization_rel MODIFY COLUMN `assignment_id` bigint NOT NULL DEFAULT 0 COMMENT '作业ID'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN assignment_organization_rel.assignment_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("organization_id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column assignment_organization_rel.organization_id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE assignment_organization_rel MODIFY COLUMN `organization_id` bigint NOT NULL DEFAULT 0 COMMENT '组织ID'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN assignment_organization_rel.organization_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("assigned_by");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column assignment_organization_rel.assigned_by " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE assignment_organization_rel MODIFY COLUMN `assigned_by` varchar(128) NOT NULL DEFAULT '' COMMENT '负责人'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN assignment_organization_rel.assigned_by failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("status");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column assignment_organization_rel.status " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE assignment_organization_rel MODIFY COLUMN `status` int NOT NULL DEFAULT 1 COMMENT '状态: 1分配 2取消'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN assignment_organization_rel.status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("is_deleted");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column assignment_organization_rel.is_deleted " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE assignment_organization_rel MODIFY COLUMN `is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN assignment_organization_rel.is_deleted failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("create_time");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column assignment_organization_rel.create_time " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE assignment_organization_rel MODIFY COLUMN `create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN assignment_organization_rel.create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("update_time");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column assignment_organization_rel.update_time " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE assignment_organization_rel MODIFY COLUMN `update_time` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '更新时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN assignment_organization_rel.update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    for (auto& [name, _] : existing_cols) {
        (void)_;
        bool found = false;
        if (name == "id") found = true;
        if (name == "assignment_id") found = true;
        if (name == "organization_id") found = true;
        if (name == "assigned_by") found = true;
        if (name == "status") found = true;
        if (name == "is_deleted") found = true;
        if (name == "create_time") found = true;
        if (name == "update_time") found = true;
        if (!found) {
            WARN(logger) << "Dropping column assignment_organization_rel." << name << " (not in schema, data will be lost)";
            int rt = conn->execute("ALTER TABLE assignment_organization_rel DROP COLUMN `" + name + "`");
            if (rt) {
                ERROR(logger) << "DROP COLUMN assignment_organization_rel." << name << " failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    if (existing_cols.find("assignment_id") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.assignment_id";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN `assignment_id` bigint NOT NULL DEFAULT 0 COMMENT '作业ID'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN assignment_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("organization_id") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.organization_id";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN `organization_id` bigint NOT NULL DEFAULT 0 COMMENT '组织ID'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN organization_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("assigned_by") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.assigned_by";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN `assigned_by` varchar(128) NOT NULL DEFAULT '' COMMENT '负责人'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN assigned_by failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("status") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.status";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN `status` int NOT NULL DEFAULT 1 COMMENT '状态: 1分配 2取消'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("is_deleted") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.is_deleted";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN `is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN is_deleted failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("create_time") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.create_time";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN `create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("update_time") == existing_cols.end()) {
        INFO(logger) << "Adding column assignment_organization_rel.update_time";
        int rt = conn->execute("ALTER TABLE assignment_organization_rel ADD COLUMN `update_time` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '更新时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE assignment_organization_rel ADD COLUMN update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}


} //namespace data
} //namespace blog
