/**
 * @file category_info.h
 * @brief 文章分类表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#pragma once

#include <vector>

#include <chen/db/db.h>
#include <chen/db/query_builder.h>
#include <chen/util/util.h>

namespace blog {
namespace data {

class CategoryInfoDao;
/**
 * @brief 文章分类表
 */
class CategoryInfo {
friend class CategoryInfoDao;
public:
    typedef std::shared_ptr<CategoryInfo> ptr;

    CategoryInfo();

    /**
     * @brief 获取id
     * @return id
     */
    const int64_t& getId() { return m_id; }
    /**
     * @brief 设置id
     * @param v id
     */
    void setId(const int64_t& v);

    /**
     * @brief 获取name
     * @return name
     */
    const std::string& getName() { return m_name; }
    /**
     * @brief 设置name
     * @param v name
     */
    void setName(const std::string& v);

    /**
     * @brief 获取color
     * @return color
     */
    const std::string& getColor() { return m_color; }
    /**
     * @brief 设置color
     * @param v color
     */
    void setColor(const std::string& v);

    /**
     * @brief 获取description
     * @return description
     */
    const std::string& getDescription() { return m_description; }
    /**
     * @brief 设置description
     * @param v description
     */
    void setDescription(const std::string& v);

    /**
     * @brief 获取url
     * @return url
     */
    const std::string& getUrl() { return m_url; }
    /**
     * @brief 设置url
     * @param v url
     */
    void setUrl(const std::string& v);

    /**
     * @brief 获取icon
     * @return icon
     */
    const std::string& getIcon() { return m_icon; }
    /**
     * @brief 设置icon
     * @param v icon
     */
    void setIcon(const std::string& v);

    /**
     * @brief 获取parent_id
     * @return parent_id
     */
    const int64_t& getParentId() { return m_parentId; }
    /**
     * @brief 设置parent_id
     * @param v parent_id
     */
    void setParentId(const int64_t& v);

    /**
     * @brief 获取0: 停用 1: 启用
     * @return 0: 停用 1: 启用
     */
    const int32_t& getStatus() { return m_status; }
    /**
     * @brief 设置0: 停用 1: 启用
     * @param v 0: 停用 1: 启用
     */
    void setStatus(const int32_t& v);

    /**
     * @brief 获取is_deleted
     * @return is_deleted
     */
    const int32_t& getIsDeleted() { return m_isDeleted; }
    /**
     * @brief 设置is_deleted
     * @param v is_deleted
     */
    void setIsDeleted(const int32_t& v);

    /**
     * @brief 获取create_time
     * @return create_time
     */
    const int64_t& getCreateTime() { return m_createTime; }
    /**
     * @brief 设置create_time
     * @param v create_time
     */
    void setCreateTime(const int64_t& v);

    /**
     * @brief 获取update_time
     * @return update_time
     */
    const int64_t& getUpdateTime() { return m_updateTime; }
    /**
     * @brief 设置update_time
     * @param v update_time
     */
    void setUpdateTime(const int64_t& v);

    /**
     * @brief 转为 JSON 字符串
     * @return JSON 字符串
     */
    std::string toJsonString() const;

    /** @brief 清除脏标记（Update 成功后自动调用） */
    void markClean() { m_flags = 0; }
    /**
     * @brief 是否有字段被修改过
     * @return true 有未保存的修改，false 无修改
     */
    bool isDirty() const { return m_flags != 0; }

private:
    int32_t m_status;
    int32_t m_isDeleted;
    int64_t m_id;
    int64_t m_parentId;
    std::string m_name;
    std::string m_color;
    std::string m_description;
    std::string m_url;
    std::string m_icon;
    int64_t m_createTime;
    int64_t m_updateTime;
    uint64_t m_flags = 0;
};


class CategoryInfoDao {
public:
    typedef std::shared_ptr<CategoryInfoDao> ptr;
    static int Update(CategoryInfo::ptr info, chen::IDB::ptr conn);
    static int Insert(CategoryInfo::ptr info, chen::IDB::ptr conn);
    static int InsertOrUpdate(CategoryInfo::ptr info, chen::IDB::ptr conn);
    static int BatchInsert(const std::vector<CategoryInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchUpdate(const std::vector<CategoryInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchDelete(const std::vector<int64_t>& ids, chen::IDB::ptr conn);
    static int Delete(CategoryInfo::ptr info, chen::IDB::ptr conn);
    static int Delete(const int64_t& id, chen::IDB::ptr conn);
    static int DeleteById( const int64_t& id, chen::IDB::ptr conn);
    static int DeleteByName( const std::string& name, chen::IDB::ptr conn);
    static int QueryAll(std::vector<CategoryInfo::ptr>& results, chen::IDB::ptr conn);
    static CategoryInfo::ptr Query( const int64_t& id, chen::IDB::ptr conn);
    static CategoryInfo::ptr QueryByName( const std::string& name, chen::IDB::ptr conn);
    static int CreateTableSQLite3(chen::IDB::ptr info);
    static int CreateTableMySQL(chen::IDB::ptr info);
    static int MigrateTableSQLite3(chen::IDB::ptr info);
    static int MigrateTableMySQL(chen::IDB::ptr info);
    static int Migrate(chen::IDB::ptr conn);
    static CategoryInfo::ptr ParseRow(chen::ISQLData::ptr data);
    static int QueryByBuilder(std::vector<CategoryInfo::ptr>& results, chen::QueryBuilder::ptr qb, chen::IDB::ptr conn);
    static int QueryByBuilderPages(std::vector<CategoryInfo::ptr>& results, int64_t& total, chen::QueryBuilder::ptr qb, int32_t offset, int32_t limit, chen::IDB::ptr conn);
};

} //namespace data
} //namespace blog
