/**
 * @file organization_apply_info.cc
 * @brief 组织创建申请表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#include "organization_apply_info.h"

#include <chen/log/log.h>

#include <map>

namespace blog {
namespace data {

static chen::Logger::ptr logger = LOG_NAME("orm");

OrganizationApplyInfo::OrganizationApplyInfo()
    :m_status(0)
    ,m_isDeleted(0)
    ,m_id()
    ,m_userId()
    ,m_createdAt()
    ,m_reviewedAt()
    ,m_orgName()
    ,m_orgType()
    ,m_orgDescription()
    ,m_reviewReason() {
}

std::string OrganizationApplyInfo::toJsonString() const {
    Json::Value v;
    v["id"] = std::to_string(m_id);
    v["user_id"] = std::to_string(m_userId);
    v["org_name"] = m_orgName;
    v["org_type"] = m_orgType;
    v["org_description"] = m_orgDescription;
    v["status"] = m_status;
    v["review_reason"] = m_reviewReason;
    v["created_at"] = std::to_string(m_createdAt);
    v["reviewed_at"] = std::to_string(m_reviewedAt);
    v["is_deleted"] = m_isDeleted;
    return chen::JsonUtil::ToString(v);
}

void OrganizationApplyInfo::setId(const int64_t& v) {
    m_id = v;
    m_flags |= (1ull << 0);
}

void OrganizationApplyInfo::setUserId(const int64_t& v) {
    m_userId = v;
    m_flags |= (1ull << 1);
}

void OrganizationApplyInfo::setOrgName(const std::string& v) {
    m_orgName = v;
    m_flags |= (1ull << 2);
}

void OrganizationApplyInfo::setOrgType(const std::string& v) {
    m_orgType = v;
    m_flags |= (1ull << 3);
}

void OrganizationApplyInfo::setOrgDescription(const std::string& v) {
    m_orgDescription = v;
    m_flags |= (1ull << 4);
}

void OrganizationApplyInfo::setStatus(const int32_t& v) {
    m_status = v;
    m_flags |= (1ull << 5);
}

void OrganizationApplyInfo::setReviewReason(const std::string& v) {
    m_reviewReason = v;
    m_flags |= (1ull << 6);
}

void OrganizationApplyInfo::setCreatedAt(const int64_t& v) {
    m_createdAt = v;
    m_flags |= (1ull << 7);
}

void OrganizationApplyInfo::setReviewedAt(const int64_t& v) {
    m_reviewedAt = v;
    m_flags |= (1ull << 8);
}

void OrganizationApplyInfo::setIsDeleted(const int32_t& v) {
    m_isDeleted = v;
    m_flags |= (1ull << 9);
}


int OrganizationApplyInfoDao::Update(OrganizationApplyInfo::ptr info, chen::IDB::ptr conn) {
    if (!info->isDirty()) {
        return 0;
    }
    std::string sql = "update organization_apply set ";
    bool first = true;
    if (info->m_flags & (1ull << 1)) {
        if (!first) sql += ", ";
        sql += "user_id = ?";
        first = false;
    }
    if (info->m_flags & (1ull << 2)) {
        if (!first) sql += ", ";
        sql += "org_name = ?";
        first = false;
    }
    if (info->m_flags & (1ull << 3)) {
        if (!first) sql += ", ";
        sql += "org_type = ?";
        first = false;
    }
    if (info->m_flags & (1ull << 4)) {
        if (!first) sql += ", ";
        sql += "org_description = ?";
        first = false;
    }
    if (info->m_flags & (1ull << 5)) {
        if (!first) sql += ", ";
        sql += "status = ?";
        first = false;
    }
    if (info->m_flags & (1ull << 6)) {
        if (!first) sql += ", ";
        sql += "review_reason = ?";
        first = false;
    }
    if (info->m_flags & (1ull << 7)) {
        if (!first) sql += ", ";
        sql += "created_at = ?";
        first = false;
    }
    if (info->m_flags & (1ull << 8)) {
        if (!first) sql += ", ";
        sql += "reviewed_at = ?";
        first = false;
    }
    if (info->m_flags & (1ull << 9)) {
        if (!first) sql += ", ";
        sql += "is_deleted = ?";
        first = false;
    }
    sql += " where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    int idx = 1;
    if (info->m_flags & (1ull << 1)) {
        stmt->bindInt64(idx++, info->m_userId);
    }
    if (info->m_flags & (1ull << 2)) {
        stmt->bindString(idx++, info->m_orgName);
    }
    if (info->m_flags & (1ull << 3)) {
        stmt->bindString(idx++, info->m_orgType);
    }
    if (info->m_flags & (1ull << 4)) {
        stmt->bindString(idx++, info->m_orgDescription);
    }
    if (info->m_flags & (1ull << 5)) {
        stmt->bindInt32(idx++, info->m_status);
    }
    if (info->m_flags & (1ull << 6)) {
        stmt->bindString(idx++, info->m_reviewReason);
    }
    if (info->m_flags & (1ull << 7)) {
        stmt->bindInt64(idx++, info->m_createdAt);
    }
    if (info->m_flags & (1ull << 8)) {
        stmt->bindInt64(idx++, info->m_reviewedAt);
    }
    if (info->m_flags & (1ull << 9)) {
        stmt->bindInt32(idx++, info->m_isDeleted);
    }
    stmt->bindInt64(idx++, info->m_id);
    int rt = stmt->execute();
    if (rt == 0) {
        info->markClean();
    }
    return rt;
}

int OrganizationApplyInfoDao::Insert(OrganizationApplyInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "insert into organization_apply (user_id, org_name, org_type, org_description, status, review_reason, created_at, reviewed_at, is_deleted) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_userId);
    stmt->bindString(2, info->m_orgName);
    stmt->bindString(3, info->m_orgType);
    stmt->bindString(4, info->m_orgDescription);
    stmt->bindInt32(5, info->m_status);
    stmt->bindString(6, info->m_reviewReason);
    stmt->bindInt64(7, info->m_createdAt);
    stmt->bindInt64(8, info->m_reviewedAt);
    stmt->bindInt32(9, info->m_isDeleted);
    int rt = stmt->execute();
    if(rt == 0) {
        info->m_id = conn->getLastInsertId();
    }
    if (rt == 0) {
        info->markClean();
    }
    return rt;
}

int OrganizationApplyInfoDao::InsertOrUpdate(OrganizationApplyInfo::ptr info, chen::IDB::ptr conn) {
    if(info->m_id == 0) {
        return Insert(info, conn);
    }
    std::string sql = "replace into organization_apply (id, user_id, org_name, org_type, org_description, status, review_reason, created_at, reviewed_at, is_deleted) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    stmt->bindInt64(2, info->m_userId);
    stmt->bindString(3, info->m_orgName);
    stmt->bindString(4, info->m_orgType);
    stmt->bindString(5, info->m_orgDescription);
    stmt->bindInt32(6, info->m_status);
    stmt->bindString(7, info->m_reviewReason);
    stmt->bindInt64(8, info->m_createdAt);
    stmt->bindInt64(9, info->m_reviewedAt);
    stmt->bindInt32(10, info->m_isDeleted);
    int rt = stmt->execute();
    if (rt == 0) {
        info->markClean();
    }
    return rt;
}

int OrganizationApplyInfoDao::BatchInsert(const std::vector<OrganizationApplyInfo::ptr>& infos, chen::IDB::ptr conn) {
    if (infos.empty()) {
        return 0;
    }
    if (!conn) {
        ERROR(logger) << "BatchInsert conn is null";
        return -1;
    }
    std::string sql = "insert into organization_apply (";
    sql += "user_id";
    sql += ", ";
    sql += "org_name";
    sql += ", ";
    sql += "org_type";
    sql += ", ";
    sql += "org_description";
    sql += ", ";
    sql += "status";
    sql += ", ";
    sql += "review_reason";
    sql += ", ";
    sql += "created_at";
    sql += ", ";
    sql += "reviewed_at";
    sql += ", ";
    sql += "is_deleted";
    sql += ") VALUES ";
    for (size_t r = 0; r < infos.size(); ++r) {
        if (r) sql += ", ";
        sql += "(";
        sql += "?";
        sql += ", ";
        sql += "?";
        sql += ", ";
        sql += "?";
        sql += ", ";
        sql += "?";
        sql += ", ";
        sql += "?";
        sql += ", ";
        sql += "?";
        sql += ", ";
        sql += "?";
        sql += ", ";
        sql += "?";
        sql += ", ";
        sql += "?";
        sql += ")";
    }
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    int idx = 1;
    for (auto& info : infos) {
        stmt->bindInt64(idx++, info->m_userId);
        stmt->bindString(idx++, info->m_orgName);
        stmt->bindString(idx++, info->m_orgType);
        stmt->bindString(idx++, info->m_orgDescription);
        stmt->bindInt32(idx++, info->m_status);
        stmt->bindString(idx++, info->m_reviewReason);
        stmt->bindInt64(idx++, info->m_createdAt);
        stmt->bindInt64(idx++, info->m_reviewedAt);
        stmt->bindInt32(idx++, info->m_isDeleted);
    }
    return stmt->execute();
}

int OrganizationApplyInfoDao::BatchUpdate(const std::vector<OrganizationApplyInfo::ptr>& infos, chen::IDB::ptr conn) {
    if (infos.empty()) {
        return 0;
    }
    if (!conn) {
        ERROR(logger) << "BatchUpdate conn is null";
        return -1;
    }
    auto trans = conn->openTransaction(true);
    if (!trans || !trans->begin()) {
        ERROR(logger) << "BatchUpdate begin transaction failed";
        return -1;
    }
    for (auto& info : infos) {
        if (Update(info, conn)) {
            ERROR(logger) << "BatchUpdate Update failed";
            trans->rollback();
            return conn->getErrno();
        }
    }
    trans->commit();
    return 0;
}

int OrganizationApplyInfoDao::BatchDelete(const std::vector<int64_t>& ids, chen::IDB::ptr conn) {
    if (ids.empty()) {
        return 0;
    }
    if (!conn) {
        ERROR(logger) << "BatchDelete conn is null";
        return -1;
    }
    std::string sql = "delete from organization_apply where id IN (";
    for (size_t i = 0; i < ids.size(); ++i) {
        if (i) sql += ", ";
        sql += "?";
    }
    sql += ")";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    int idx = 1;
    for (auto& id : ids) {
        stmt->bindInt64(idx++, id);
    }
    return stmt->execute();
}

int OrganizationApplyInfoDao::Delete(OrganizationApplyInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "delete from organization_apply where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    return stmt->execute();
}

int OrganizationApplyInfoDao::DeleteById( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "delete from organization_apply where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, id);
    return stmt->execute();
}

int OrganizationApplyInfoDao::DeleteByUserId( const int64_t& user_id, chen::IDB::ptr conn) {
    std::string sql = "delete from organization_apply where user_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, user_id);
    return stmt->execute();
}

int OrganizationApplyInfoDao::DeleteByStatus( const int32_t& status, chen::IDB::ptr conn) {
    std::string sql = "delete from organization_apply where status = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt32(1, status);
    return stmt->execute();
}

int OrganizationApplyInfoDao::QueryAll(std::vector<OrganizationApplyInfo::ptr>& results, chen::IDB::ptr conn) {
    std::string sql = "select id, user_id, org_name, org_type, org_description, status, review_reason, created_at, reviewed_at, is_deleted from organization_apply";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    auto rt = stmt->query();
    if(!rt) {
        return stmt->getErrno();
    }
    while (rt->next()) {
        OrganizationApplyInfo::ptr v(new OrganizationApplyInfo);
        v->m_id = rt->getInt64(0);
        v->m_userId = rt->getInt64(1);
        v->m_orgName = rt->getString(2);
        v->m_orgType = rt->getString(3);
        v->m_orgDescription = rt->getString(4);
        v->m_status = rt->getInt32(5);
        v->m_reviewReason = rt->getString(6);
        v->m_createdAt = rt->getInt64(7);
        v->m_reviewedAt = rt->getInt64(8);
        v->m_isDeleted = rt->getInt32(9);
        results.push_back(v);
    }
    return 0;
}

OrganizationApplyInfo::ptr OrganizationApplyInfoDao::Query( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "select id, user_id, org_name, org_type, org_description, status, review_reason, created_at, reviewed_at, is_deleted from organization_apply where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindInt64(1, id);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    OrganizationApplyInfo::ptr v(new OrganizationApplyInfo);
    v->m_id = rt->getInt64(0);
    v->m_userId = rt->getInt64(1);
    v->m_orgName = rt->getString(2);
    v->m_orgType = rt->getString(3);
    v->m_orgDescription = rt->getString(4);
    v->m_status = rt->getInt32(5);
    v->m_reviewReason = rt->getString(6);
    v->m_createdAt = rt->getInt64(7);
    v->m_reviewedAt = rt->getInt64(8);
    v->m_isDeleted = rt->getInt32(9);
    return v;
}

int OrganizationApplyInfoDao::QueryByUserId(std::vector<OrganizationApplyInfo::ptr>& results,  const int64_t& user_id, chen::IDB::ptr conn) {
    std::string sql = "select id, user_id, org_name, org_type, org_description, status, review_reason, created_at, reviewed_at, is_deleted from organization_apply where user_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, user_id);
    auto rt = stmt->query();
    if(!rt) {
        return 0;
    }
    while (rt->next()) {
        OrganizationApplyInfo::ptr v(new OrganizationApplyInfo);
        v->m_id = rt->getInt64(0);
        v->m_userId = rt->getInt64(1);
        v->m_orgName = rt->getString(2);
        v->m_orgType = rt->getString(3);
        v->m_orgDescription = rt->getString(4);
        v->m_status = rt->getInt32(5);
        v->m_reviewReason = rt->getString(6);
        v->m_createdAt = rt->getInt64(7);
        v->m_reviewedAt = rt->getInt64(8);
        v->m_isDeleted = rt->getInt32(9);
        results.push_back(v);
    };
    return 0;
}

int OrganizationApplyInfoDao::QueryByUserIdPages(std::vector<OrganizationApplyInfo::ptr>& results, int64_t& total,  const int64_t& user_id, int32_t offset, int32_t limit, chen::IDB::ptr conn) {
    std::string countSql = "select count(*) from organization_apply where user_id = ?";
    auto countStmt = conn->prepare(countSql);
    if (!countStmt) {
        ERROR(logger) << "stmt=" << countSql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    countStmt->bindInt64(1, user_id);
    auto countRt = countStmt->query();
    if (!countRt) {
        return countStmt->getErrno();
    }
    if (countRt->next()) {
        total = countRt->getInt64(0);
    }
    if (total == 0) {
        return 0;
    }
    std::string sql = "select id, user_id, org_name, org_type, org_description, status, review_reason, created_at, reviewed_at, is_deleted from organization_apply where user_id = ? order by id desc limit ? offset ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, user_id);
    stmt->bindInt32(2, limit);
    stmt->bindInt32(3, offset);
    auto rt = stmt->query();
    if (!rt) {
        return 0;
    }
    while (rt->next()) {
        OrganizationApplyInfo::ptr v(new OrganizationApplyInfo);
        v->m_id = rt->getInt64(0);
        v->m_userId = rt->getInt64(1);
        v->m_orgName = rt->getString(2);
        v->m_orgType = rt->getString(3);
        v->m_orgDescription = rt->getString(4);
        v->m_status = rt->getInt32(5);
        v->m_reviewReason = rt->getString(6);
        v->m_createdAt = rt->getInt64(7);
        v->m_reviewedAt = rt->getInt64(8);
        v->m_isDeleted = rt->getInt32(9);
        results.push_back(v);
    };
    return 0;
}

int OrganizationApplyInfoDao::QueryByStatus(std::vector<OrganizationApplyInfo::ptr>& results,  const int32_t& status, chen::IDB::ptr conn) {
    std::string sql = "select id, user_id, org_name, org_type, org_description, status, review_reason, created_at, reviewed_at, is_deleted from organization_apply where status = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt32(1, status);
    auto rt = stmt->query();
    if(!rt) {
        return 0;
    }
    while (rt->next()) {
        OrganizationApplyInfo::ptr v(new OrganizationApplyInfo);
        v->m_id = rt->getInt64(0);
        v->m_userId = rt->getInt64(1);
        v->m_orgName = rt->getString(2);
        v->m_orgType = rt->getString(3);
        v->m_orgDescription = rt->getString(4);
        v->m_status = rt->getInt32(5);
        v->m_reviewReason = rt->getString(6);
        v->m_createdAt = rt->getInt64(7);
        v->m_reviewedAt = rt->getInt64(8);
        v->m_isDeleted = rt->getInt32(9);
        results.push_back(v);
    };
    return 0;
}

int OrganizationApplyInfoDao::QueryByStatusPages(std::vector<OrganizationApplyInfo::ptr>& results, int64_t& total,  const int32_t& status, int32_t offset, int32_t limit, chen::IDB::ptr conn) {
    std::string countSql = "select count(*) from organization_apply where status = ?";
    auto countStmt = conn->prepare(countSql);
    if (!countStmt) {
        ERROR(logger) << "stmt=" << countSql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    countStmt->bindInt32(1, status);
    auto countRt = countStmt->query();
    if (!countRt) {
        return countStmt->getErrno();
    }
    if (countRt->next()) {
        total = countRt->getInt64(0);
    }
    if (total == 0) {
        return 0;
    }
    std::string sql = "select id, user_id, org_name, org_type, org_description, status, review_reason, created_at, reviewed_at, is_deleted from organization_apply where status = ? order by id desc limit ? offset ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt32(1, status);
    stmt->bindInt32(2, limit);
    stmt->bindInt32(3, offset);
    auto rt = stmt->query();
    if (!rt) {
        return 0;
    }
    while (rt->next()) {
        OrganizationApplyInfo::ptr v(new OrganizationApplyInfo);
        v->m_id = rt->getInt64(0);
        v->m_userId = rt->getInt64(1);
        v->m_orgName = rt->getString(2);
        v->m_orgType = rt->getString(3);
        v->m_orgDescription = rt->getString(4);
        v->m_status = rt->getInt32(5);
        v->m_reviewReason = rt->getString(6);
        v->m_createdAt = rt->getInt64(7);
        v->m_reviewedAt = rt->getInt64(8);
        v->m_isDeleted = rt->getInt32(9);
        results.push_back(v);
    };
    return 0;
}

OrganizationApplyInfo::ptr OrganizationApplyInfoDao::ParseRow(chen::ISQLData::ptr data) {
    if (!data) {
        ERROR(logger) << "ParseRow data is null";
        return nullptr;
    }
    OrganizationApplyInfo::ptr v(new OrganizationApplyInfo);
    v->m_id = data->getInt64(0);
    v->m_userId = data->getInt64(1);
    v->m_orgName = data->getString(2);
    v->m_orgType = data->getString(3);
    v->m_orgDescription = data->getString(4);
    v->m_status = data->getInt32(5);
    v->m_reviewReason = data->getString(6);
    v->m_createdAt = data->getInt64(7);
    v->m_reviewedAt = data->getInt64(8);
    v->m_isDeleted = data->getInt32(9);
    return v;
}

int OrganizationApplyInfoDao::QueryByBuilder(std::vector<OrganizationApplyInfo::ptr>& results, chen::QueryBuilder::ptr qb, chen::IDB::ptr conn) {
    if (!qb || !conn) {
        ERROR(logger) << "QueryByBuilder qb or conn is null";
        return -1;
    }
    std::string sql = qb->buildQuerySQL("id, user_id, org_name, org_type, org_description, status, review_reason, created_at, reviewed_at, is_deleted");
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    qb->bindParams(stmt);
    auto rt = stmt->query();
    if(!rt) {
        return stmt->getErrno();
    }
    while (rt->next()) {
        OrganizationApplyInfo::ptr v(new OrganizationApplyInfo);
        v->m_id = rt->getInt64(0);
        v->m_userId = rt->getInt64(1);
        v->m_orgName = rt->getString(2);
        v->m_orgType = rt->getString(3);
        v->m_orgDescription = rt->getString(4);
        v->m_status = rt->getInt32(5);
        v->m_reviewReason = rt->getString(6);
        v->m_createdAt = rt->getInt64(7);
        v->m_reviewedAt = rt->getInt64(8);
        v->m_isDeleted = rt->getInt32(9);
        results.push_back(v);
    }
    return 0;
}

int OrganizationApplyInfoDao::QueryByBuilderPages(std::vector<OrganizationApplyInfo::ptr>& results, int64_t& total, chen::QueryBuilder::ptr qb, int32_t offset, int32_t limit, chen::IDB::ptr conn) {
    if (!qb || !conn) {
        ERROR(logger) << "QueryByBuilderPages qb or conn is null";
        return -1;
    }
    std::string countSql = qb->buildCountSQL();
    auto countStmt = conn->prepare(countSql);
    if (!countStmt) {
        ERROR(logger) << "stmt=" << countSql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    qb->bindQueryParams(countStmt);
    auto countRt = countStmt->query();
    if (!countRt) {
        return countStmt->getErrno();
    }
    if (countRt->next()) {
        total = countRt->getInt64(0);
    }
    if (total == 0) {
        return 0;
    }
    std::string sql = qb->buildQuerySQL("id, user_id, org_name, org_type, org_description, status, review_reason, created_at, reviewed_at, is_deleted", false);
    if (!qb->hasOrderBy()) {
        sql += " order by id desc";
    }
    sql += " limit ? offset ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
            << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    qb->bindQueryParams(stmt);
    int idx = qb->getQueryParamCount() + 1;
    stmt->bindInt32(idx++, limit);
    stmt->bindInt32(idx++, offset);
    auto rt = stmt->query();
    if (!rt) {
        return 0;
    }
    while (rt->next()) {
        OrganizationApplyInfo::ptr v(new OrganizationApplyInfo);
        v->m_id = rt->getInt64(0);
        v->m_userId = rt->getInt64(1);
        v->m_orgName = rt->getString(2);
        v->m_orgType = rt->getString(3);
        v->m_orgDescription = rt->getString(4);
        v->m_status = rt->getInt32(5);
        v->m_reviewReason = rt->getString(6);
        v->m_createdAt = rt->getInt64(7);
        v->m_reviewedAt = rt->getInt64(8);
        v->m_isDeleted = rt->getInt32(9);
        results.push_back(v);
    }
    return 0;
}

int OrganizationApplyInfoDao::CreateTableSQLite3(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS organization_apply("
            "id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "user_id INTEGER NOT NULL DEFAULT 0,"
            "org_name TEXT NOT NULL DEFAULT '',"
            "org_type TEXT NOT NULL DEFAULT '',"
            "org_description TEXT NOT NULL DEFAULT '',"
            "status INTEGER NOT NULL DEFAULT 0,"
            "review_reason TEXT NOT NULL DEFAULT '',"
            "created_at INTEGER NOT NULL DEFAULT 0,"
            "reviewed_at INTEGER NOT NULL DEFAULT 0,"
            "is_deleted INTEGER NOT NULL DEFAULT 0);"
            "CREATE INDEX IF NOT EXISTS organization_apply_user_id ON organization_apply(user_id);"
            "CREATE INDEX IF NOT EXISTS organization_apply_status ON organization_apply(status);"
            );
}

int OrganizationApplyInfoDao::CreateTableMySQL(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS organization_apply("
            "`id` bigint AUTO_INCREMENT COMMENT '申请ID',"
            "`user_id` bigint NOT NULL DEFAULT 0 COMMENT '申请人用户ID',"
            "`org_name` varchar(100) NOT NULL DEFAULT '' COMMENT '组织名称',"
            "`org_type` varchar(50) NOT NULL DEFAULT '' COMMENT '组织类型',"
            "`org_description` varchar(500) NOT NULL DEFAULT '' COMMENT '组织描述',"
            "`status` int NOT NULL DEFAULT 0 COMMENT '状态: 0待审核 1已通过 2已拒绝',"
            "`review_reason` varchar(500) NOT NULL DEFAULT '' COMMENT '审核备注',"
            "`created_at` bigint NOT NULL DEFAULT 0 COMMENT '申请时间(unix timestamp)',"
            "`reviewed_at` bigint NOT NULL DEFAULT 0 COMMENT '审核时间(unix timestamp)',"
            "`is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除',"
            "PRIMARY KEY(`id`),"
            "KEY `organization_apply_user_id` (`user_id`),"
            "KEY `organization_apply_status` (`status`)) COMMENT='组织创建申请表'");
}

int OrganizationApplyInfoDao::Migrate(chen::IDB::ptr conn) {
    if (!conn) {
        ERROR(logger) << "Migrate conn is null";
        return -1;
    }

    conn->execute("CREATE TABLE IF NOT EXISTS schema_version ("
        "table_name VARCHAR(128) PRIMARY KEY, "
        "version INT NOT NULL DEFAULT 0)");

    auto verStmt = conn->prepare("SELECT version FROM schema_version WHERE table_name = ?");
    if (!verStmt) {
        ERROR(logger) << "Migrate prepare version query failed errno=" << conn->getErrno();
        return conn->getErrno();
    }
    verStmt->bindString(1, "organization_apply");
    auto verRt = verStmt->query();
    int dbVer = 0;
    if (verRt && verRt->next()) {
        dbVer = (int)verRt->getInt64(0);
    }

    if (dbVer < 1) {
        if (CreateTableSQLite3(conn)) {
            ERROR(logger) << "Migrate v1 CreateTable failed";
            return conn->getErrno();
        }
    }

    if (dbVer == 0) {
        auto insStmt = conn->prepare("INSERT INTO schema_version (table_name, version) VALUES (?, ?)");
        if (insStmt) {
            insStmt->bindString(1, "organization_apply");
            insStmt->bindInt32(2, 1);
            insStmt->execute();
        }
    } else {
        auto updStmt = conn->prepare("UPDATE schema_version SET version = ? WHERE table_name = ?");
        if (updStmt) {
            updStmt->bindInt32(1, 1);
            updStmt->bindString(2, "organization_apply");
            updStmt->execute();
        }
    }
    return 0;
}

int OrganizationApplyInfoDao::MigrateTableSQLite3(chen::IDB::ptr conn) {
    auto data = conn->query("PRAGMA table_info(organization_apply)");
    if (!data) {
        ERROR(logger) << "PRAGMA table_info(organization_apply) errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(1)] = data->getString(2);
    }

    bool need_recreate = false;
    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_apply.id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("user_id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_apply.user_id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("org_name");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_apply.org_name " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("org_type");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_apply.org_type " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("org_description");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_apply.org_description " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("status");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_apply.status " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("review_reason");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_apply.review_reason " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("created_at");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_apply.created_at " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("reviewed_at");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_apply.reviewed_at " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("is_deleted");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_apply.is_deleted " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    if (!need_recreate) {
        for (auto& [name, _] : existing_cols) {
            (void)_;  // suppress unused warning
            bool found = false;
            if (name == "id") found = true;
            if (name == "user_id") found = true;
            if (name == "org_name") found = true;
            if (name == "org_type") found = true;
            if (name == "org_description") found = true;
            if (name == "status") found = true;
            if (name == "review_reason") found = true;
            if (name == "created_at") found = true;
            if (name == "reviewed_at") found = true;
            if (name == "is_deleted") found = true;
            if (!found) {
                need_recreate = true;
                WARN(logger) << "Column organization_apply." << name << " removed, table recreate required";
                break;
            }
        }
    }

    if (need_recreate) {
        INFO(logger) << "Recreating table organization_apply";

        std::vector<std::string> common_cols;
        if (existing_cols.find("id") != existing_cols.end()) {
            common_cols.push_back("id");
        }
        if (existing_cols.find("user_id") != existing_cols.end()) {
            common_cols.push_back("user_id");
        }
        if (existing_cols.find("org_name") != existing_cols.end()) {
            common_cols.push_back("org_name");
        }
        if (existing_cols.find("org_type") != existing_cols.end()) {
            common_cols.push_back("org_type");
        }
        if (existing_cols.find("org_description") != existing_cols.end()) {
            common_cols.push_back("org_description");
        }
        if (existing_cols.find("status") != existing_cols.end()) {
            common_cols.push_back("status");
        }
        if (existing_cols.find("review_reason") != existing_cols.end()) {
            common_cols.push_back("review_reason");
        }
        if (existing_cols.find("created_at") != existing_cols.end()) {
            common_cols.push_back("created_at");
        }
        if (existing_cols.find("reviewed_at") != existing_cols.end()) {
            common_cols.push_back("reviewed_at");
        }
        if (existing_cols.find("is_deleted") != existing_cols.end()) {
            common_cols.push_back("is_deleted");
        }

        if (conn->execute("ALTER TABLE organization_apply RENAME TO organization_apply_tmp")) {
            ERROR(logger) << "RENAME TABLE organization_apply failed";
            return conn->getErrno();
        }
        CreateTableSQLite3(conn);
        if (!common_cols.empty()) {
            std::string cols;
            for (size_t i = 0; i < common_cols.size(); ++i) {
                if (i) cols += ",";
                cols += common_cols[i];
            }
            std::string sql = "INSERT INTO organization_apply (" + cols + ") SELECT " + cols + " FROM organization_apply_tmp";
            if (int rt = conn->execute(sql)) {
                ERROR(logger) << "copy data from organization_apply_tmp to organization_apply failed, errno=" << rt;
                // don't return; try to continue
            }
        }
        conn->execute("DROP TABLE organization_apply_tmp");
        return 0;
    }

    if (existing_cols.find("user_id") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.user_id";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN user_id INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN user_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("org_name") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.org_name";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN org_name TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN org_name failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("org_type") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.org_type";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN org_type TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN org_type failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("org_description") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.org_description";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN org_description TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN org_description failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("status") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.status";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN status INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("review_reason") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.review_reason";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN review_reason TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN review_reason failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("created_at") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.created_at";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN created_at INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN created_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("reviewed_at") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.reviewed_at";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN reviewed_at INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN reviewed_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("is_deleted") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.is_deleted";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN is_deleted failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}

int OrganizationApplyInfoDao::MigrateTableMySQL(chen::IDB::ptr conn) {
    auto data = conn->query("SHOW COLUMNS FROM organization_apply");
    if (!data) {
        ERROR(logger) << "SHOW COLUMNS FROM organization_apply errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(0)] = data->getString(1);
    }

    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column organization_apply.id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE organization_apply MODIFY COLUMN `id` bigint NOT NULL DEFAULT 0 COMMENT '申请ID'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_apply.id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("user_id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column organization_apply.user_id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE organization_apply MODIFY COLUMN `user_id` bigint NOT NULL DEFAULT 0 COMMENT '申请人用户ID'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_apply.user_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("org_name");
        if (it != existing_cols.end() && it->second != "varchar(100)") {
            INFO(logger) << "Modifying column organization_apply.org_name " << it->second << " -> varchar(100)";
            int rt = conn->execute("ALTER TABLE organization_apply MODIFY COLUMN `org_name` varchar(100) NOT NULL DEFAULT '' COMMENT '组织名称'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_apply.org_name failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("org_type");
        if (it != existing_cols.end() && it->second != "varchar(50)") {
            INFO(logger) << "Modifying column organization_apply.org_type " << it->second << " -> varchar(50)";
            int rt = conn->execute("ALTER TABLE organization_apply MODIFY COLUMN `org_type` varchar(50) NOT NULL DEFAULT '' COMMENT '组织类型'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_apply.org_type failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("org_description");
        if (it != existing_cols.end() && it->second != "varchar(500)") {
            INFO(logger) << "Modifying column organization_apply.org_description " << it->second << " -> varchar(500)";
            int rt = conn->execute("ALTER TABLE organization_apply MODIFY COLUMN `org_description` varchar(500) NOT NULL DEFAULT '' COMMENT '组织描述'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_apply.org_description failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("status");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column organization_apply.status " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE organization_apply MODIFY COLUMN `status` int NOT NULL DEFAULT 0 COMMENT '状态: 0待审核 1已通过 2已拒绝'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_apply.status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("review_reason");
        if (it != existing_cols.end() && it->second != "varchar(500)") {
            INFO(logger) << "Modifying column organization_apply.review_reason " << it->second << " -> varchar(500)";
            int rt = conn->execute("ALTER TABLE organization_apply MODIFY COLUMN `review_reason` varchar(500) NOT NULL DEFAULT '' COMMENT '审核备注'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_apply.review_reason failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("created_at");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column organization_apply.created_at " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE organization_apply MODIFY COLUMN `created_at` bigint NOT NULL DEFAULT 0 COMMENT '申请时间(unix timestamp)'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_apply.created_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("reviewed_at");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column organization_apply.reviewed_at " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE organization_apply MODIFY COLUMN `reviewed_at` bigint NOT NULL DEFAULT 0 COMMENT '审核时间(unix timestamp)'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_apply.reviewed_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("is_deleted");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column organization_apply.is_deleted " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE organization_apply MODIFY COLUMN `is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_apply.is_deleted failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    for (auto& [name, _] : existing_cols) {
        (void)_;
        bool found = false;
        if (name == "id") found = true;
        if (name == "user_id") found = true;
        if (name == "org_name") found = true;
        if (name == "org_type") found = true;
        if (name == "org_description") found = true;
        if (name == "status") found = true;
        if (name == "review_reason") found = true;
        if (name == "created_at") found = true;
        if (name == "reviewed_at") found = true;
        if (name == "is_deleted") found = true;
        if (!found) {
            WARN(logger) << "Dropping column organization_apply." << name << " (not in schema, data will be lost)";
            int rt = conn->execute("ALTER TABLE organization_apply DROP COLUMN `" + name + "`");
            if (rt) {
                ERROR(logger) << "DROP COLUMN organization_apply." << name << " failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    if (existing_cols.find("user_id") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.user_id";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN `user_id` bigint NOT NULL DEFAULT 0 COMMENT '申请人用户ID'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN user_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("org_name") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.org_name";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN `org_name` varchar(100) NOT NULL DEFAULT '' COMMENT '组织名称'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN org_name failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("org_type") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.org_type";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN `org_type` varchar(50) NOT NULL DEFAULT '' COMMENT '组织类型'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN org_type failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("org_description") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.org_description";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN `org_description` varchar(500) NOT NULL DEFAULT '' COMMENT '组织描述'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN org_description failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("status") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.status";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN `status` int NOT NULL DEFAULT 0 COMMENT '状态: 0待审核 1已通过 2已拒绝'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("review_reason") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.review_reason";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN `review_reason` varchar(500) NOT NULL DEFAULT '' COMMENT '审核备注'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN review_reason failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("created_at") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.created_at";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN `created_at` bigint NOT NULL DEFAULT 0 COMMENT '申请时间(unix timestamp)'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN created_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("reviewed_at") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.reviewed_at";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN `reviewed_at` bigint NOT NULL DEFAULT 0 COMMENT '审核时间(unix timestamp)'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN reviewed_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("is_deleted") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_apply.is_deleted";
        int rt = conn->execute("ALTER TABLE organization_apply ADD COLUMN `is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_apply ADD COLUMN is_deleted failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}


} //namespace data
} //namespace blog
