/**
 * @file organization_repo_prs_info.cc
 * @brief 组织仓库 PR 表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#include "organization_repo_prs_info.h"

#include <chen/log/log.h>

#include <map>

namespace blog {
namespace data {

static chen::Logger::ptr logger = LOG_NAME("orm");

OrganizationRepoPrsInfo::OrganizationRepoPrsInfo()
    :m_githubPrId()
    ,m_changedFiles(0)
    ,m_additions(0)
    ,m_deletions(0)
    ,m_id()
    ,m_repoId()
    ,m_title()
    ,m_description()
    ,m_state()
    ,m_priority()
    ,m_author()
    ,m_headBranch()
    ,m_baseBranch()
    ,m_commitSha()
    ,m_reviewers()
    ,m_reviewStatus()
    ,m_closedAt()
    ,m_mergedAt()
    ,m_createTime(time(0))
    ,m_updateTime() {
}

std::string OrganizationRepoPrsInfo::toJsonString() const {
    Json::Value v;
    v["id"] = std::to_string(m_id);
    v["repo_id"] = std::to_string(m_repoId);
    v["github_pr_id"] = m_githubPrId;
    v["title"] = m_title;
    v["description"] = m_description;
    v["state"] = m_state;
    v["priority"] = m_priority;
    v["author"] = m_author;
    v["head_branch"] = m_headBranch;
    v["base_branch"] = m_baseBranch;
    v["commit_sha"] = m_commitSha;
    v["changed_files"] = m_changedFiles;
    v["additions"] = m_additions;
    v["deletions"] = m_deletions;
    v["reviewers"] = m_reviewers;
    v["review_status"] = m_reviewStatus;
    v["closed_at"] = chen::Time2Str(m_closedAt);
    v["merged_at"] = chen::Time2Str(m_mergedAt);
    v["create_time"] = chen::Time2Str(m_createTime);
    v["update_time"] = chen::Time2Str(m_updateTime);
    return chen::JsonUtil::ToString(v);
}

void OrganizationRepoPrsInfo::setId(const int64_t& v) {
    m_id = v;
}

void OrganizationRepoPrsInfo::setRepoId(const int64_t& v) {
    m_repoId = v;
}

void OrganizationRepoPrsInfo::setGithubPrId(const int32_t& v) {
    m_githubPrId = v;
}

void OrganizationRepoPrsInfo::setTitle(const std::string& v) {
    m_title = v;
}

void OrganizationRepoPrsInfo::setDescription(const std::string& v) {
    m_description = v;
}

void OrganizationRepoPrsInfo::setState(const std::string& v) {
    m_state = v;
}

void OrganizationRepoPrsInfo::setPriority(const std::string& v) {
    m_priority = v;
}

void OrganizationRepoPrsInfo::setAuthor(const std::string& v) {
    m_author = v;
}

void OrganizationRepoPrsInfo::setHeadBranch(const std::string& v) {
    m_headBranch = v;
}

void OrganizationRepoPrsInfo::setBaseBranch(const std::string& v) {
    m_baseBranch = v;
}

void OrganizationRepoPrsInfo::setCommitSha(const std::string& v) {
    m_commitSha = v;
}

void OrganizationRepoPrsInfo::setChangedFiles(const int32_t& v) {
    m_changedFiles = v;
}

void OrganizationRepoPrsInfo::setAdditions(const int32_t& v) {
    m_additions = v;
}

void OrganizationRepoPrsInfo::setDeletions(const int32_t& v) {
    m_deletions = v;
}

void OrganizationRepoPrsInfo::setReviewers(const std::string& v) {
    m_reviewers = v;
}

void OrganizationRepoPrsInfo::setReviewStatus(const std::string& v) {
    m_reviewStatus = v;
}

void OrganizationRepoPrsInfo::setClosedAt(const int64_t& v) {
    m_closedAt = v;
}

void OrganizationRepoPrsInfo::setMergedAt(const int64_t& v) {
    m_mergedAt = v;
}

void OrganizationRepoPrsInfo::setCreateTime(const int64_t& v) {
    m_createTime = v;
}

void OrganizationRepoPrsInfo::setUpdateTime(const int64_t& v) {
    m_updateTime = v;
}


int OrganizationRepoPrsInfoDao::Update(OrganizationRepoPrsInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "update organization_repo_prs set repo_id = ?, github_pr_id = ?, title = ?, description = ?, state = ?, priority = ?, author = ?, head_branch = ?, base_branch = ?, commit_sha = ?, changed_files = ?, additions = ?, deletions = ?, reviewers = ?, review_status = ?, closed_at = ?, merged_at = ?, create_time = ?, update_time = ? where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_repoId);
    stmt->bindInt32(2, info->m_githubPrId);
    stmt->bindString(3, info->m_title);
    stmt->bindString(4, info->m_description);
    stmt->bindString(5, info->m_state);
    stmt->bindString(6, info->m_priority);
    stmt->bindString(7, info->m_author);
    stmt->bindString(8, info->m_headBranch);
    stmt->bindString(9, info->m_baseBranch);
    stmt->bindString(10, info->m_commitSha);
    stmt->bindInt32(11, info->m_changedFiles);
    stmt->bindInt32(12, info->m_additions);
    stmt->bindInt32(13, info->m_deletions);
    stmt->bindString(14, info->m_reviewers);
    stmt->bindString(15, info->m_reviewStatus);
    stmt->bindTime(16, info->m_closedAt);
    stmt->bindTime(17, info->m_mergedAt);
    stmt->bindTime(18, info->m_createTime);
    stmt->bindTime(19, info->m_updateTime);
    stmt->bindInt64(20, info->m_id);
    return stmt->execute();
}

int OrganizationRepoPrsInfoDao::Insert(OrganizationRepoPrsInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "insert into organization_repo_prs (repo_id, github_pr_id, title, description, state, priority, author, head_branch, base_branch, commit_sha, changed_files, additions, deletions, reviewers, review_status, closed_at, merged_at, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_repoId);
    stmt->bindInt32(2, info->m_githubPrId);
    stmt->bindString(3, info->m_title);
    stmt->bindString(4, info->m_description);
    stmt->bindString(5, info->m_state);
    stmt->bindString(6, info->m_priority);
    stmt->bindString(7, info->m_author);
    stmt->bindString(8, info->m_headBranch);
    stmt->bindString(9, info->m_baseBranch);
    stmt->bindString(10, info->m_commitSha);
    stmt->bindInt32(11, info->m_changedFiles);
    stmt->bindInt32(12, info->m_additions);
    stmt->bindInt32(13, info->m_deletions);
    stmt->bindString(14, info->m_reviewers);
    stmt->bindString(15, info->m_reviewStatus);
    stmt->bindTime(16, info->m_closedAt);
    stmt->bindTime(17, info->m_mergedAt);
    stmt->bindTime(18, info->m_createTime);
    stmt->bindTime(19, info->m_updateTime);
    int rt = stmt->execute();
    if(rt == 0) {
        info->m_id = conn->getLastInsertId();
    }
    return rt;
}

int OrganizationRepoPrsInfoDao::InsertOrUpdate(OrganizationRepoPrsInfo::ptr info, chen::IDB::ptr conn) {
    if(info->m_id == 0) {
        return Insert(info, conn);
    }
    std::string sql = "replace into organization_repo_prs (id, repo_id, github_pr_id, title, description, state, priority, author, head_branch, base_branch, commit_sha, changed_files, additions, deletions, reviewers, review_status, closed_at, merged_at, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    stmt->bindInt64(2, info->m_repoId);
    stmt->bindInt32(3, info->m_githubPrId);
    stmt->bindString(4, info->m_title);
    stmt->bindString(5, info->m_description);
    stmt->bindString(6, info->m_state);
    stmt->bindString(7, info->m_priority);
    stmt->bindString(8, info->m_author);
    stmt->bindString(9, info->m_headBranch);
    stmt->bindString(10, info->m_baseBranch);
    stmt->bindString(11, info->m_commitSha);
    stmt->bindInt32(12, info->m_changedFiles);
    stmt->bindInt32(13, info->m_additions);
    stmt->bindInt32(14, info->m_deletions);
    stmt->bindString(15, info->m_reviewers);
    stmt->bindString(16, info->m_reviewStatus);
    stmt->bindTime(17, info->m_closedAt);
    stmt->bindTime(18, info->m_mergedAt);
    stmt->bindTime(19, info->m_createTime);
    stmt->bindTime(20, info->m_updateTime);
    return stmt->execute();
}

int OrganizationRepoPrsInfoDao::Delete(OrganizationRepoPrsInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "delete from organization_repo_prs where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    return stmt->execute();
}

int OrganizationRepoPrsInfoDao::DeleteById( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "delete from organization_repo_prs where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, id);
    return stmt->execute();
}

int OrganizationRepoPrsInfoDao::DeleteByRepoId( const int64_t& repo_id, chen::IDB::ptr conn) {
    std::string sql = "delete from organization_repo_prs where repo_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, repo_id);
    return stmt->execute();
}

int OrganizationRepoPrsInfoDao::DeleteByRepoIdGithubPrId( const int64_t& repo_id,  const int32_t& github_pr_id, chen::IDB::ptr conn) {
    std::string sql = "delete from organization_repo_prs where repo_id = ? and github_pr_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, repo_id);
    stmt->bindInt32(1, github_pr_id);
    return stmt->execute();
}

int OrganizationRepoPrsInfoDao::QueryAll(std::vector<OrganizationRepoPrsInfo::ptr>& results, chen::IDB::ptr conn) {
    std::string sql = "select id, repo_id, github_pr_id, title, description, state, priority, author, head_branch, base_branch, commit_sha, changed_files, additions, deletions, reviewers, review_status, closed_at, merged_at, create_time, update_time from organization_repo_prs";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    auto rt = stmt->query();
    if(!rt) {
        return stmt->getErrno();
    }
    while (rt->next()) {
        OrganizationRepoPrsInfo::ptr v(new OrganizationRepoPrsInfo);
        v->m_id = rt->getInt64(0);
        v->m_repoId = rt->getInt64(1);
        v->m_githubPrId = rt->getInt32(2);
        v->m_title = rt->getString(3);
        v->m_description = rt->getString(4);
        v->m_state = rt->getString(5);
        v->m_priority = rt->getString(6);
        v->m_author = rt->getString(7);
        v->m_headBranch = rt->getString(8);
        v->m_baseBranch = rt->getString(9);
        v->m_commitSha = rt->getString(10);
        v->m_changedFiles = rt->getInt32(11);
        v->m_additions = rt->getInt32(12);
        v->m_deletions = rt->getInt32(13);
        v->m_reviewers = rt->getString(14);
        v->m_reviewStatus = rt->getString(15);
        v->m_closedAt = rt->getTime(16);
        v->m_mergedAt = rt->getTime(17);
        v->m_createTime = rt->getTime(18);
        v->m_updateTime = rt->getTime(19);
        results.push_back(v);
    }
    return 0;
}

OrganizationRepoPrsInfo::ptr OrganizationRepoPrsInfoDao::Query( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "select id, repo_id, github_pr_id, title, description, state, priority, author, head_branch, base_branch, commit_sha, changed_files, additions, deletions, reviewers, review_status, closed_at, merged_at, create_time, update_time from organization_repo_prs where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindInt64(1, id);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    OrganizationRepoPrsInfo::ptr v(new OrganizationRepoPrsInfo);
    v->m_id = rt->getInt64(0);
    v->m_repoId = rt->getInt64(1);
    v->m_githubPrId = rt->getInt32(2);
    v->m_title = rt->getString(3);
    v->m_description = rt->getString(4);
    v->m_state = rt->getString(5);
    v->m_priority = rt->getString(6);
    v->m_author = rt->getString(7);
    v->m_headBranch = rt->getString(8);
    v->m_baseBranch = rt->getString(9);
    v->m_commitSha = rt->getString(10);
    v->m_changedFiles = rt->getInt32(11);
    v->m_additions = rt->getInt32(12);
    v->m_deletions = rt->getInt32(13);
    v->m_reviewers = rt->getString(14);
    v->m_reviewStatus = rt->getString(15);
    v->m_closedAt = rt->getTime(16);
    v->m_mergedAt = rt->getTime(17);
    v->m_createTime = rt->getTime(18);
    v->m_updateTime = rt->getTime(19);
    return v;
}

int OrganizationRepoPrsInfoDao::QueryByRepoId(std::vector<OrganizationRepoPrsInfo::ptr>& results,  const int64_t& repo_id, chen::IDB::ptr conn) {
    std::string sql = "select id, repo_id, github_pr_id, title, description, state, priority, author, head_branch, base_branch, commit_sha, changed_files, additions, deletions, reviewers, review_status, closed_at, merged_at, create_time, update_time from organization_repo_prs where repo_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, repo_id);
    auto rt = stmt->query();
    if(!rt) {
        return 0;
    }
    while (rt->next()) {
        OrganizationRepoPrsInfo::ptr v(new OrganizationRepoPrsInfo);
        v->m_id = rt->getInt64(0);
        v->m_repoId = rt->getInt64(1);
        v->m_githubPrId = rt->getInt32(2);
        v->m_title = rt->getString(3);
        v->m_description = rt->getString(4);
        v->m_state = rt->getString(5);
        v->m_priority = rt->getString(6);
        v->m_author = rt->getString(7);
        v->m_headBranch = rt->getString(8);
        v->m_baseBranch = rt->getString(9);
        v->m_commitSha = rt->getString(10);
        v->m_changedFiles = rt->getInt32(11);
        v->m_additions = rt->getInt32(12);
        v->m_deletions = rt->getInt32(13);
        v->m_reviewers = rt->getString(14);
        v->m_reviewStatus = rt->getString(15);
        v->m_closedAt = rt->getTime(16);
        v->m_mergedAt = rt->getTime(17);
        v->m_createTime = rt->getTime(18);
        v->m_updateTime = rt->getTime(19);
        results.push_back(v);
    };
    return 0;
}

int OrganizationRepoPrsInfoDao::QueryByRepoIdPages(std::vector<OrganizationRepoPrsInfo::ptr>& results, int64_t& total,  const int64_t& repo_id, int32_t offset, int32_t limit, chen::IDB::ptr conn) {
    std::string countSql = "select count(*) from organization_repo_prs where repo_id = ?";
    auto countStmt = conn->prepare(countSql);
    if (!countStmt) {
        ERROR(logger) << "stmt=" << countSql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    countStmt->bindInt64(1, repo_id);
    auto countRt = countStmt->query();
    if (!countRt) {
        return countStmt->getErrno();
    }
    if (countRt->next()) {
        total = countRt->getInt64(0);
    }
    if (total == 0) {
        return 0;
    }
    std::string sql = "select id, repo_id, github_pr_id, title, description, state, priority, author, head_branch, base_branch, commit_sha, changed_files, additions, deletions, reviewers, review_status, closed_at, merged_at, create_time, update_time from organization_repo_prs where repo_id = ? order by id desc limit ? offset ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, repo_id);
    stmt->bindInt32(2, limit);
    stmt->bindInt32(3, offset);
    auto rt = stmt->query();
    if (!rt) {
        return 0;
    }
    while (rt->next()) {
        OrganizationRepoPrsInfo::ptr v(new OrganizationRepoPrsInfo);
        v->m_id = rt->getInt64(0);
        v->m_repoId = rt->getInt64(1);
        v->m_githubPrId = rt->getInt32(2);
        v->m_title = rt->getString(3);
        v->m_description = rt->getString(4);
        v->m_state = rt->getString(5);
        v->m_priority = rt->getString(6);
        v->m_author = rt->getString(7);
        v->m_headBranch = rt->getString(8);
        v->m_baseBranch = rt->getString(9);
        v->m_commitSha = rt->getString(10);
        v->m_changedFiles = rt->getInt32(11);
        v->m_additions = rt->getInt32(12);
        v->m_deletions = rt->getInt32(13);
        v->m_reviewers = rt->getString(14);
        v->m_reviewStatus = rt->getString(15);
        v->m_closedAt = rt->getTime(16);
        v->m_mergedAt = rt->getTime(17);
        v->m_createTime = rt->getTime(18);
        v->m_updateTime = rt->getTime(19);
        results.push_back(v);
    };
    return 0;
}

OrganizationRepoPrsInfo::ptr OrganizationRepoPrsInfoDao::QueryByRepoIdGithubPrId( const int64_t& repo_id,  const int32_t& github_pr_id, chen::IDB::ptr conn) {
    std::string sql = "select id, repo_id, github_pr_id, title, description, state, priority, author, head_branch, base_branch, commit_sha, changed_files, additions, deletions, reviewers, review_status, closed_at, merged_at, create_time, update_time from organization_repo_prs where repo_id = ? and github_pr_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindInt64(1, repo_id);
    stmt->bindInt32(2, github_pr_id);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    OrganizationRepoPrsInfo::ptr v(new OrganizationRepoPrsInfo);
    v->m_id = rt->getInt64(0);
    v->m_repoId = rt->getInt64(1);
    v->m_githubPrId = rt->getInt32(2);
    v->m_title = rt->getString(3);
    v->m_description = rt->getString(4);
    v->m_state = rt->getString(5);
    v->m_priority = rt->getString(6);
    v->m_author = rt->getString(7);
    v->m_headBranch = rt->getString(8);
    v->m_baseBranch = rt->getString(9);
    v->m_commitSha = rt->getString(10);
    v->m_changedFiles = rt->getInt32(11);
    v->m_additions = rt->getInt32(12);
    v->m_deletions = rt->getInt32(13);
    v->m_reviewers = rt->getString(14);
    v->m_reviewStatus = rt->getString(15);
    v->m_closedAt = rt->getTime(16);
    v->m_mergedAt = rt->getTime(17);
    v->m_createTime = rt->getTime(18);
    v->m_updateTime = rt->getTime(19);
    return v;
}

int OrganizationRepoPrsInfoDao::CreateTableSQLite3(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS organization_repo_prs("
            "id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "repo_id INTEGER NOT NULL DEFAULT 0,"
            "github_pr_id INTEGER NOT NULL DEFAULT 0,"
            "title TEXT NOT NULL DEFAULT '',"
            "description TEXT NOT NULL DEFAULT '',"
            "state TEXT NOT NULL DEFAULT '',"
            "priority TEXT NOT NULL DEFAULT '',"
            "author TEXT NOT NULL DEFAULT '',"
            "head_branch TEXT NOT NULL DEFAULT '',"
            "base_branch TEXT NOT NULL DEFAULT '',"
            "commit_sha TEXT NOT NULL DEFAULT '',"
            "changed_files INTEGER NOT NULL DEFAULT 0,"
            "additions INTEGER NOT NULL DEFAULT 0,"
            "deletions INTEGER NOT NULL DEFAULT 0,"
            "reviewers TEXT NOT NULL DEFAULT '',"
            "review_status TEXT NOT NULL DEFAULT '',"
            "closed_at TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00',"
            "merged_at TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00',"
            "create_time TIMESTAMP NOT NULL DEFAULT current_timestamp,"
            "update_time TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00');"
            "CREATE INDEX IF NOT EXISTS organization_repo_prs_repo_id ON organization_repo_prs(repo_id);"
            "CREATE UNIQUE INDEX IF NOT EXISTS organization_repo_prs_repo_id_github_pr_id ON organization_repo_prs(repo_id,github_pr_id);"
            );
}

int OrganizationRepoPrsInfoDao::CreateTableMySQL(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS organization_repo_prs("
            "`id` bigint AUTO_INCREMENT COMMENT '主键',"
            "`repo_id` bigint NOT NULL DEFAULT 0 COMMENT '仓库 ID，关联 organization_repos 表',"
            "`github_pr_id` int NOT NULL DEFAULT 0 COMMENT 'GitHub PR 编号，用于幂等去重',"
            "`title` varchar(256) NOT NULL DEFAULT '' COMMENT 'PR 标题',"
            "`description` varchar(4096) NOT NULL DEFAULT '' COMMENT 'PR 描述',"
            "`state` varchar(16) NOT NULL DEFAULT '' COMMENT '状态: open/closed/merged',"
            "`priority` varchar(16) NOT NULL DEFAULT '' COMMENT '优先级: low/medium/high/critical',"
            "`author` varchar(128) NOT NULL DEFAULT '' COMMENT '作者 GitHub 用户名',"
            "`head_branch` varchar(256) NOT NULL DEFAULT '' COMMENT '源分支',"
            "`base_branch` varchar(256) NOT NULL DEFAULT '' COMMENT '目标分支',"
            "`commit_sha` varchar(64) NOT NULL DEFAULT '' COMMENT '最新 Commit SHA',"
            "`changed_files` int NOT NULL DEFAULT 0 COMMENT '变更文件数',"
            "`additions` int NOT NULL DEFAULT 0 COMMENT '新增行数',"
            "`deletions` int NOT NULL DEFAULT 0 COMMENT '删除行数',"
            "`reviewers` varchar(1024) NOT NULL DEFAULT '' COMMENT '审核人信息 JSON 数组',"
            "`review_status` varchar(32) NOT NULL DEFAULT '' COMMENT '审核状态: pending/approved/changes_requested',"
            "`closed_at` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '关闭时间',"
            "`merged_at` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '合并时间',"
            "`create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '记录创建时间',"
            "`update_time` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' ON UPDATE current_timestamp  COMMENT '记录更新时间',"
            "PRIMARY KEY(`id`),"
            "KEY `organization_repo_prs_repo_id` (`repo_id`),"
            "UNIQUE KEY `organization_repo_prs_repo_id_github_pr_id` (`repo_id`,`github_pr_id`)) COMMENT='组织仓库 PR 表'");
}

int OrganizationRepoPrsInfoDao::MigrateTableSQLite3(chen::IDB::ptr conn) {
    auto data = conn->query("PRAGMA table_info(organization_repo_prs)");
    if (!data) {
        ERROR(logger) << "PRAGMA table_info(organization_repo_prs) errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(1)] = data->getString(2);
    }

    bool need_recreate = false;
    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_repo_prs.id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("repo_id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_repo_prs.repo_id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("github_pr_id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_repo_prs.github_pr_id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("title");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_repo_prs.title " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("description");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_repo_prs.description " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("state");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_repo_prs.state " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("priority");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_repo_prs.priority " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("author");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_repo_prs.author " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("head_branch");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_repo_prs.head_branch " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("base_branch");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_repo_prs.base_branch " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("commit_sha");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_repo_prs.commit_sha " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("changed_files");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_repo_prs.changed_files " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("additions");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_repo_prs.additions " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("deletions");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: organization_repo_prs.deletions " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("reviewers");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_repo_prs.reviewers " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("review_status");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: organization_repo_prs.review_status " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("closed_at");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: organization_repo_prs.closed_at " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("merged_at");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: organization_repo_prs.merged_at " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("create_time");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: organization_repo_prs.create_time " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("update_time");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: organization_repo_prs.update_time " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    if (!need_recreate) {
        for (auto& [name, _] : existing_cols) {
            (void)_;  // suppress unused warning
            bool found = false;
            if (name == "id") found = true;
            if (name == "repo_id") found = true;
            if (name == "github_pr_id") found = true;
            if (name == "title") found = true;
            if (name == "description") found = true;
            if (name == "state") found = true;
            if (name == "priority") found = true;
            if (name == "author") found = true;
            if (name == "head_branch") found = true;
            if (name == "base_branch") found = true;
            if (name == "commit_sha") found = true;
            if (name == "changed_files") found = true;
            if (name == "additions") found = true;
            if (name == "deletions") found = true;
            if (name == "reviewers") found = true;
            if (name == "review_status") found = true;
            if (name == "closed_at") found = true;
            if (name == "merged_at") found = true;
            if (name == "create_time") found = true;
            if (name == "update_time") found = true;
            if (!found) {
                need_recreate = true;
                WARN(logger) << "Column organization_repo_prs." << name << " removed, table recreate required";
                break;
            }
        }
    }

    if (need_recreate) {
        INFO(logger) << "Recreating table organization_repo_prs";

        std::vector<std::string> common_cols;
        if (existing_cols.find("id") != existing_cols.end()) {
            common_cols.push_back("id");
        }
        if (existing_cols.find("repo_id") != existing_cols.end()) {
            common_cols.push_back("repo_id");
        }
        if (existing_cols.find("github_pr_id") != existing_cols.end()) {
            common_cols.push_back("github_pr_id");
        }
        if (existing_cols.find("title") != existing_cols.end()) {
            common_cols.push_back("title");
        }
        if (existing_cols.find("description") != existing_cols.end()) {
            common_cols.push_back("description");
        }
        if (existing_cols.find("state") != existing_cols.end()) {
            common_cols.push_back("state");
        }
        if (existing_cols.find("priority") != existing_cols.end()) {
            common_cols.push_back("priority");
        }
        if (existing_cols.find("author") != existing_cols.end()) {
            common_cols.push_back("author");
        }
        if (existing_cols.find("head_branch") != existing_cols.end()) {
            common_cols.push_back("head_branch");
        }
        if (existing_cols.find("base_branch") != existing_cols.end()) {
            common_cols.push_back("base_branch");
        }
        if (existing_cols.find("commit_sha") != existing_cols.end()) {
            common_cols.push_back("commit_sha");
        }
        if (existing_cols.find("changed_files") != existing_cols.end()) {
            common_cols.push_back("changed_files");
        }
        if (existing_cols.find("additions") != existing_cols.end()) {
            common_cols.push_back("additions");
        }
        if (existing_cols.find("deletions") != existing_cols.end()) {
            common_cols.push_back("deletions");
        }
        if (existing_cols.find("reviewers") != existing_cols.end()) {
            common_cols.push_back("reviewers");
        }
        if (existing_cols.find("review_status") != existing_cols.end()) {
            common_cols.push_back("review_status");
        }
        if (existing_cols.find("closed_at") != existing_cols.end()) {
            common_cols.push_back("closed_at");
        }
        if (existing_cols.find("merged_at") != existing_cols.end()) {
            common_cols.push_back("merged_at");
        }
        if (existing_cols.find("create_time") != existing_cols.end()) {
            common_cols.push_back("create_time");
        }
        if (existing_cols.find("update_time") != existing_cols.end()) {
            common_cols.push_back("update_time");
        }

        if (conn->execute("ALTER TABLE organization_repo_prs RENAME TO organization_repo_prs_tmp")) {
            ERROR(logger) << "RENAME TABLE organization_repo_prs failed";
            return conn->getErrno();
        }
        CreateTableSQLite3(conn);
        if (!common_cols.empty()) {
            std::string cols;
            for (size_t i = 0; i < common_cols.size(); ++i) {
                if (i) cols += ",";
                cols += common_cols[i];
            }
            std::string sql = "INSERT INTO organization_repo_prs (" + cols + ") SELECT " + cols + " FROM organization_repo_prs_tmp";
            if (int rt = conn->execute(sql)) {
                ERROR(logger) << "copy data from organization_repo_prs_tmp to organization_repo_prs failed, errno=" << rt;
                // don't return; try to continue
            }
        }
        conn->execute("DROP TABLE organization_repo_prs_tmp");
        return 0;
    }

    if (existing_cols.find("repo_id") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.repo_id";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN repo_id INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN repo_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("github_pr_id") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.github_pr_id";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN github_pr_id INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN github_pr_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("title") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.title";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN title TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN title failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("description") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.description";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN description TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN description failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("state") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.state";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN state TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN state failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("priority") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.priority";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN priority TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN priority failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("author") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.author";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN author TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN author failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("head_branch") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.head_branch";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN head_branch TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN head_branch failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("base_branch") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.base_branch";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN base_branch TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN base_branch failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("commit_sha") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.commit_sha";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN commit_sha TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN commit_sha failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("changed_files") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.changed_files";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN changed_files INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN changed_files failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("additions") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.additions";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN additions INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN additions failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("deletions") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.deletions";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN deletions INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN deletions failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("reviewers") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.reviewers";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN reviewers TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN reviewers failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("review_status") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.review_status";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN review_status TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN review_status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("closed_at") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.closed_at";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN closed_at TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN closed_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("merged_at") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.merged_at";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN merged_at TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN merged_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("create_time") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.create_time";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN create_time TIMESTAMP NOT NULL DEFAULT current_timestamp");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("update_time") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.update_time";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN update_time TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}

int OrganizationRepoPrsInfoDao::MigrateTableMySQL(chen::IDB::ptr conn) {
    auto data = conn->query("SHOW COLUMNS FROM organization_repo_prs");
    if (!data) {
        ERROR(logger) << "SHOW COLUMNS FROM organization_repo_prs errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(0)] = data->getString(1);
    }

    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column organization_repo_prs.id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `id` bigint NOT NULL DEFAULT 0 COMMENT '主键'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("repo_id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column organization_repo_prs.repo_id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `repo_id` bigint NOT NULL DEFAULT 0 COMMENT '仓库 ID，关联 organization_repos 表'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.repo_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("github_pr_id");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column organization_repo_prs.github_pr_id " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `github_pr_id` int NOT NULL DEFAULT 0 COMMENT 'GitHub PR 编号，用于幂等去重'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.github_pr_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("title");
        if (it != existing_cols.end() && it->second != "varchar(256)") {
            INFO(logger) << "Modifying column organization_repo_prs.title " << it->second << " -> varchar(256)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `title` varchar(256) NOT NULL DEFAULT '' COMMENT 'PR 标题'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.title failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("description");
        if (it != existing_cols.end() && it->second != "varchar(4096)") {
            INFO(logger) << "Modifying column organization_repo_prs.description " << it->second << " -> varchar(4096)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `description` varchar(4096) NOT NULL DEFAULT '' COMMENT 'PR 描述'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.description failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("state");
        if (it != existing_cols.end() && it->second != "varchar(16)") {
            INFO(logger) << "Modifying column organization_repo_prs.state " << it->second << " -> varchar(16)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `state` varchar(16) NOT NULL DEFAULT '' COMMENT '状态: open/closed/merged'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.state failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("priority");
        if (it != existing_cols.end() && it->second != "varchar(16)") {
            INFO(logger) << "Modifying column organization_repo_prs.priority " << it->second << " -> varchar(16)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `priority` varchar(16) NOT NULL DEFAULT '' COMMENT '优先级: low/medium/high/critical'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.priority failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("author");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column organization_repo_prs.author " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `author` varchar(128) NOT NULL DEFAULT '' COMMENT '作者 GitHub 用户名'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.author failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("head_branch");
        if (it != existing_cols.end() && it->second != "varchar(256)") {
            INFO(logger) << "Modifying column organization_repo_prs.head_branch " << it->second << " -> varchar(256)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `head_branch` varchar(256) NOT NULL DEFAULT '' COMMENT '源分支'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.head_branch failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("base_branch");
        if (it != existing_cols.end() && it->second != "varchar(256)") {
            INFO(logger) << "Modifying column organization_repo_prs.base_branch " << it->second << " -> varchar(256)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `base_branch` varchar(256) NOT NULL DEFAULT '' COMMENT '目标分支'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.base_branch failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("commit_sha");
        if (it != existing_cols.end() && it->second != "varchar(64)") {
            INFO(logger) << "Modifying column organization_repo_prs.commit_sha " << it->second << " -> varchar(64)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `commit_sha` varchar(64) NOT NULL DEFAULT '' COMMENT '最新 Commit SHA'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.commit_sha failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("changed_files");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column organization_repo_prs.changed_files " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `changed_files` int NOT NULL DEFAULT 0 COMMENT '变更文件数'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.changed_files failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("additions");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column organization_repo_prs.additions " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `additions` int NOT NULL DEFAULT 0 COMMENT '新增行数'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.additions failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("deletions");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column organization_repo_prs.deletions " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `deletions` int NOT NULL DEFAULT 0 COMMENT '删除行数'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.deletions failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("reviewers");
        if (it != existing_cols.end() && it->second != "varchar(1024)") {
            INFO(logger) << "Modifying column organization_repo_prs.reviewers " << it->second << " -> varchar(1024)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `reviewers` varchar(1024) NOT NULL DEFAULT '' COMMENT '审核人信息 JSON 数组'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.reviewers failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("review_status");
        if (it != existing_cols.end() && it->second != "varchar(32)") {
            INFO(logger) << "Modifying column organization_repo_prs.review_status " << it->second << " -> varchar(32)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `review_status` varchar(32) NOT NULL DEFAULT '' COMMENT '审核状态: pending/approved/changes_requested'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.review_status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("closed_at");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column organization_repo_prs.closed_at " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `closed_at` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '关闭时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.closed_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("merged_at");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column organization_repo_prs.merged_at " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `merged_at` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '合并时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.merged_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("create_time");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column organization_repo_prs.create_time " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '记录创建时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("update_time");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column organization_repo_prs.update_time " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE organization_repo_prs MODIFY COLUMN `update_time` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '记录更新时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN organization_repo_prs.update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    for (auto& [name, _] : existing_cols) {
        (void)_;
        bool found = false;
        if (name == "id") found = true;
        if (name == "repo_id") found = true;
        if (name == "github_pr_id") found = true;
        if (name == "title") found = true;
        if (name == "description") found = true;
        if (name == "state") found = true;
        if (name == "priority") found = true;
        if (name == "author") found = true;
        if (name == "head_branch") found = true;
        if (name == "base_branch") found = true;
        if (name == "commit_sha") found = true;
        if (name == "changed_files") found = true;
        if (name == "additions") found = true;
        if (name == "deletions") found = true;
        if (name == "reviewers") found = true;
        if (name == "review_status") found = true;
        if (name == "closed_at") found = true;
        if (name == "merged_at") found = true;
        if (name == "create_time") found = true;
        if (name == "update_time") found = true;
        if (!found) {
            WARN(logger) << "Dropping column organization_repo_prs." << name << " (not in schema, data will be lost)";
            int rt = conn->execute("ALTER TABLE organization_repo_prs DROP COLUMN `" + name + "`");
            if (rt) {
                ERROR(logger) << "DROP COLUMN organization_repo_prs." << name << " failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    if (existing_cols.find("repo_id") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.repo_id";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `repo_id` bigint NOT NULL DEFAULT 0 COMMENT '仓库 ID，关联 organization_repos 表'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN repo_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("github_pr_id") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.github_pr_id";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `github_pr_id` int NOT NULL DEFAULT 0 COMMENT 'GitHub PR 编号，用于幂等去重'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN github_pr_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("title") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.title";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `title` varchar(256) NOT NULL DEFAULT '' COMMENT 'PR 标题'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN title failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("description") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.description";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `description` varchar(4096) NOT NULL DEFAULT '' COMMENT 'PR 描述'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN description failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("state") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.state";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `state` varchar(16) NOT NULL DEFAULT '' COMMENT '状态: open/closed/merged'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN state failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("priority") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.priority";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `priority` varchar(16) NOT NULL DEFAULT '' COMMENT '优先级: low/medium/high/critical'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN priority failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("author") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.author";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `author` varchar(128) NOT NULL DEFAULT '' COMMENT '作者 GitHub 用户名'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN author failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("head_branch") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.head_branch";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `head_branch` varchar(256) NOT NULL DEFAULT '' COMMENT '源分支'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN head_branch failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("base_branch") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.base_branch";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `base_branch` varchar(256) NOT NULL DEFAULT '' COMMENT '目标分支'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN base_branch failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("commit_sha") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.commit_sha";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `commit_sha` varchar(64) NOT NULL DEFAULT '' COMMENT '最新 Commit SHA'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN commit_sha failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("changed_files") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.changed_files";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `changed_files` int NOT NULL DEFAULT 0 COMMENT '变更文件数'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN changed_files failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("additions") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.additions";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `additions` int NOT NULL DEFAULT 0 COMMENT '新增行数'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN additions failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("deletions") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.deletions";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `deletions` int NOT NULL DEFAULT 0 COMMENT '删除行数'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN deletions failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("reviewers") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.reviewers";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `reviewers` varchar(1024) NOT NULL DEFAULT '' COMMENT '审核人信息 JSON 数组'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN reviewers failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("review_status") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.review_status";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `review_status` varchar(32) NOT NULL DEFAULT '' COMMENT '审核状态: pending/approved/changes_requested'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN review_status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("closed_at") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.closed_at";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `closed_at` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '关闭时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN closed_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("merged_at") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.merged_at";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `merged_at` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '合并时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN merged_at failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("create_time") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.create_time";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '记录创建时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("update_time") == existing_cols.end()) {
        INFO(logger) << "Adding column organization_repo_prs.update_time";
        int rt = conn->execute("ALTER TABLE organization_repo_prs ADD COLUMN `update_time` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '记录更新时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE organization_repo_prs ADD COLUMN update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}


} //namespace data
} //namespace blog
