/**
 * @file requirement_info.cc
 * @brief 需求表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#include "requirement_info.h"

#include <chen/log/log.h>

#include <map>

namespace blog {
namespace data {

static chen::Logger::ptr logger = LOG_NAME("orm");

RequirementInfo::RequirementInfo()
    :m_priority(1)
    ,m_status(0)
    ,m_isDeleted(0)
    ,m_id()
    ,m_orgId()
    ,m_creatorId()
    ,m_assigneeId()
    ,m_title()
    ,m_description()
    ,m_iteration()
    ,m_category()
    ,m_source()
    ,m_deadline()
    ,m_createTime(time(0))
    ,m_updateTime() {
}

std::string RequirementInfo::toJsonString() const {
    Json::Value v;
    v["id"] = std::to_string(m_id);
    v["org_id"] = std::to_string(m_orgId);
    v["title"] = m_title;
    v["description"] = m_description;
    v["priority"] = m_priority;
    v["status"] = m_status;
    v["creator_id"] = std::to_string(m_creatorId);
    v["assignee_id"] = std::to_string(m_assigneeId);
    v["iteration"] = m_iteration;
    v["category"] = m_category;
    v["source"] = m_source;
    v["deadline"] = chen::Time2Str(m_deadline);
    v["is_deleted"] = m_isDeleted;
    v["create_time"] = chen::Time2Str(m_createTime);
    v["update_time"] = chen::Time2Str(m_updateTime);
    return chen::JsonUtil::ToString(v);
}

void RequirementInfo::setId(const int64_t& v) {
    m_id = v;
}

void RequirementInfo::setOrgId(const int64_t& v) {
    m_orgId = v;
}

void RequirementInfo::setTitle(const std::string& v) {
    m_title = v;
}

void RequirementInfo::setDescription(const std::string& v) {
    m_description = v;
}

void RequirementInfo::setPriority(const int32_t& v) {
    m_priority = v;
}

void RequirementInfo::setStatus(const int32_t& v) {
    m_status = v;
}

void RequirementInfo::setCreatorId(const int64_t& v) {
    m_creatorId = v;
}

void RequirementInfo::setAssigneeId(const int64_t& v) {
    m_assigneeId = v;
}

void RequirementInfo::setIteration(const std::string& v) {
    m_iteration = v;
}

void RequirementInfo::setCategory(const std::string& v) {
    m_category = v;
}

void RequirementInfo::setSource(const std::string& v) {
    m_source = v;
}

void RequirementInfo::setDeadline(const int64_t& v) {
    m_deadline = v;
}

void RequirementInfo::setIsDeleted(const int32_t& v) {
    m_isDeleted = v;
}

void RequirementInfo::setCreateTime(const int64_t& v) {
    m_createTime = v;
}

void RequirementInfo::setUpdateTime(const int64_t& v) {
    m_updateTime = v;
}


int RequirementInfoDao::Update(RequirementInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "update requirement set org_id = ?, title = ?, description = ?, priority = ?, status = ?, creator_id = ?, assignee_id = ?, iteration = ?, category = ?, source = ?, deadline = ?, is_deleted = ?, create_time = ?, update_time = ? where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_orgId);
    stmt->bindString(2, info->m_title);
    stmt->bindString(3, info->m_description);
    stmt->bindInt32(4, info->m_priority);
    stmt->bindInt32(5, info->m_status);
    stmt->bindInt64(6, info->m_creatorId);
    stmt->bindInt64(7, info->m_assigneeId);
    stmt->bindString(8, info->m_iteration);
    stmt->bindString(9, info->m_category);
    stmt->bindString(10, info->m_source);
    stmt->bindTime(11, info->m_deadline);
    stmt->bindInt32(12, info->m_isDeleted);
    stmt->bindTime(13, info->m_createTime);
    stmt->bindTime(14, info->m_updateTime);
    stmt->bindInt64(15, info->m_id);
    return stmt->execute();
}

int RequirementInfoDao::Insert(RequirementInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "insert into requirement (org_id, title, description, priority, status, creator_id, assignee_id, iteration, category, source, deadline, is_deleted, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_orgId);
    stmt->bindString(2, info->m_title);
    stmt->bindString(3, info->m_description);
    stmt->bindInt32(4, info->m_priority);
    stmt->bindInt32(5, info->m_status);
    stmt->bindInt64(6, info->m_creatorId);
    stmt->bindInt64(7, info->m_assigneeId);
    stmt->bindString(8, info->m_iteration);
    stmt->bindString(9, info->m_category);
    stmt->bindString(10, info->m_source);
    stmt->bindTime(11, info->m_deadline);
    stmt->bindInt32(12, info->m_isDeleted);
    stmt->bindTime(13, info->m_createTime);
    stmt->bindTime(14, info->m_updateTime);
    int rt = stmt->execute();
    if(rt == 0) {
        info->m_id = conn->getLastInsertId();
    }
    return rt;
}

int RequirementInfoDao::InsertOrUpdate(RequirementInfo::ptr info, chen::IDB::ptr conn) {
    if(info->m_id == 0) {
        return Insert(info, conn);
    }
    std::string sql = "replace into requirement (id, org_id, title, description, priority, status, creator_id, assignee_id, iteration, category, source, deadline, is_deleted, create_time, update_time) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    stmt->bindInt64(2, info->m_orgId);
    stmt->bindString(3, info->m_title);
    stmt->bindString(4, info->m_description);
    stmt->bindInt32(5, info->m_priority);
    stmt->bindInt32(6, info->m_status);
    stmt->bindInt64(7, info->m_creatorId);
    stmt->bindInt64(8, info->m_assigneeId);
    stmt->bindString(9, info->m_iteration);
    stmt->bindString(10, info->m_category);
    stmt->bindString(11, info->m_source);
    stmt->bindTime(12, info->m_deadline);
    stmt->bindInt32(13, info->m_isDeleted);
    stmt->bindTime(14, info->m_createTime);
    stmt->bindTime(15, info->m_updateTime);
    return stmt->execute();
}

int RequirementInfoDao::Delete(RequirementInfo::ptr info, chen::IDB::ptr conn) {
    std::string sql = "delete from requirement where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, info->m_id);
    return stmt->execute();
}

int RequirementInfoDao::DeleteById( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "delete from requirement where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, id);
    return stmt->execute();
}

int RequirementInfoDao::DeleteByOrgId( const int64_t& org_id, chen::IDB::ptr conn) {
    std::string sql = "delete from requirement where org_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, org_id);
    return stmt->execute();
}

int RequirementInfoDao::DeleteByCreatorId( const int64_t& creator_id, chen::IDB::ptr conn) {
    std::string sql = "delete from requirement where creator_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, creator_id);
    return stmt->execute();
}

int RequirementInfoDao::DeleteByAssigneeId( const int64_t& assignee_id, chen::IDB::ptr conn) {
    std::string sql = "delete from requirement where assignee_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, assignee_id);
    return stmt->execute();
}

int RequirementInfoDao::QueryAll(std::vector<RequirementInfo::ptr>& results, chen::IDB::ptr conn) {
    std::string sql = "select id, org_id, title, description, priority, status, creator_id, assignee_id, iteration, category, source, deadline, is_deleted, create_time, update_time from requirement";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    auto rt = stmt->query();
    if(!rt) {
        return stmt->getErrno();
    }
    while (rt->next()) {
        RequirementInfo::ptr v(new RequirementInfo);
        v->m_id = rt->getInt64(0);
        v->m_orgId = rt->getInt64(1);
        v->m_title = rt->getString(2);
        v->m_description = rt->getString(3);
        v->m_priority = rt->getInt32(4);
        v->m_status = rt->getInt32(5);
        v->m_creatorId = rt->getInt64(6);
        v->m_assigneeId = rt->getInt64(7);
        v->m_iteration = rt->getString(8);
        v->m_category = rt->getString(9);
        v->m_source = rt->getString(10);
        v->m_deadline = rt->getTime(11);
        v->m_isDeleted = rt->getInt32(12);
        v->m_createTime = rt->getTime(13);
        v->m_updateTime = rt->getTime(14);
        results.push_back(v);
    }
    return 0;
}

RequirementInfo::ptr RequirementInfoDao::Query( const int64_t& id, chen::IDB::ptr conn) {
    std::string sql = "select id, org_id, title, description, priority, status, creator_id, assignee_id, iteration, category, source, deadline, is_deleted, create_time, update_time from requirement where id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return nullptr;
    }
    stmt->bindInt64(1, id);
    auto rt = stmt->query();
    if(!rt) {
        return nullptr;
    }
    if(!rt->next()) {
        return nullptr;
    }
    RequirementInfo::ptr v(new RequirementInfo);
    v->m_id = rt->getInt64(0);
    v->m_orgId = rt->getInt64(1);
    v->m_title = rt->getString(2);
    v->m_description = rt->getString(3);
    v->m_priority = rt->getInt32(4);
    v->m_status = rt->getInt32(5);
    v->m_creatorId = rt->getInt64(6);
    v->m_assigneeId = rt->getInt64(7);
    v->m_iteration = rt->getString(8);
    v->m_category = rt->getString(9);
    v->m_source = rt->getString(10);
    v->m_deadline = rt->getTime(11);
    v->m_isDeleted = rt->getInt32(12);
    v->m_createTime = rt->getTime(13);
    v->m_updateTime = rt->getTime(14);
    return v;
}

int RequirementInfoDao::QueryByOrgId(std::vector<RequirementInfo::ptr>& results,  const int64_t& org_id, chen::IDB::ptr conn) {
    std::string sql = "select id, org_id, title, description, priority, status, creator_id, assignee_id, iteration, category, source, deadline, is_deleted, create_time, update_time from requirement where org_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, org_id);
    auto rt = stmt->query();
    if(!rt) {
        return 0;
    }
    while (rt->next()) {
        RequirementInfo::ptr v(new RequirementInfo);
        v->m_id = rt->getInt64(0);
        v->m_orgId = rt->getInt64(1);
        v->m_title = rt->getString(2);
        v->m_description = rt->getString(3);
        v->m_priority = rt->getInt32(4);
        v->m_status = rt->getInt32(5);
        v->m_creatorId = rt->getInt64(6);
        v->m_assigneeId = rt->getInt64(7);
        v->m_iteration = rt->getString(8);
        v->m_category = rt->getString(9);
        v->m_source = rt->getString(10);
        v->m_deadline = rt->getTime(11);
        v->m_isDeleted = rt->getInt32(12);
        v->m_createTime = rt->getTime(13);
        v->m_updateTime = rt->getTime(14);
        results.push_back(v);
    };
    return 0;
}

int RequirementInfoDao::QueryByOrgIdPages(std::vector<RequirementInfo::ptr>& results, int64_t& total,  const int64_t& org_id, int32_t offset, int32_t limit, chen::IDB::ptr conn) {
    std::string countSql = "select count(*) from requirement where org_id = ?";
    auto countStmt = conn->prepare(countSql);
    if (!countStmt) {
        ERROR(logger) << "stmt=" << countSql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    countStmt->bindInt64(1, org_id);
    auto countRt = countStmt->query();
    if (!countRt) {
        return countStmt->getErrno();
    }
    if (countRt->next()) {
        total = countRt->getInt64(0);
    }
    if (total == 0) {
        return 0;
    }
    std::string sql = "select id, org_id, title, description, priority, status, creator_id, assignee_id, iteration, category, source, deadline, is_deleted, create_time, update_time from requirement where org_id = ? order by id desc limit ? offset ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, org_id);
    stmt->bindInt32(2, limit);
    stmt->bindInt32(3, offset);
    auto rt = stmt->query();
    if (!rt) {
        return 0;
    }
    while (rt->next()) {
        RequirementInfo::ptr v(new RequirementInfo);
        v->m_id = rt->getInt64(0);
        v->m_orgId = rt->getInt64(1);
        v->m_title = rt->getString(2);
        v->m_description = rt->getString(3);
        v->m_priority = rt->getInt32(4);
        v->m_status = rt->getInt32(5);
        v->m_creatorId = rt->getInt64(6);
        v->m_assigneeId = rt->getInt64(7);
        v->m_iteration = rt->getString(8);
        v->m_category = rt->getString(9);
        v->m_source = rt->getString(10);
        v->m_deadline = rt->getTime(11);
        v->m_isDeleted = rt->getInt32(12);
        v->m_createTime = rt->getTime(13);
        v->m_updateTime = rt->getTime(14);
        results.push_back(v);
    };
    return 0;
}

int RequirementInfoDao::QueryByCreatorId(std::vector<RequirementInfo::ptr>& results,  const int64_t& creator_id, chen::IDB::ptr conn) {
    std::string sql = "select id, org_id, title, description, priority, status, creator_id, assignee_id, iteration, category, source, deadline, is_deleted, create_time, update_time from requirement where creator_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, creator_id);
    auto rt = stmt->query();
    if(!rt) {
        return 0;
    }
    while (rt->next()) {
        RequirementInfo::ptr v(new RequirementInfo);
        v->m_id = rt->getInt64(0);
        v->m_orgId = rt->getInt64(1);
        v->m_title = rt->getString(2);
        v->m_description = rt->getString(3);
        v->m_priority = rt->getInt32(4);
        v->m_status = rt->getInt32(5);
        v->m_creatorId = rt->getInt64(6);
        v->m_assigneeId = rt->getInt64(7);
        v->m_iteration = rt->getString(8);
        v->m_category = rt->getString(9);
        v->m_source = rt->getString(10);
        v->m_deadline = rt->getTime(11);
        v->m_isDeleted = rt->getInt32(12);
        v->m_createTime = rt->getTime(13);
        v->m_updateTime = rt->getTime(14);
        results.push_back(v);
    };
    return 0;
}

int RequirementInfoDao::QueryByCreatorIdPages(std::vector<RequirementInfo::ptr>& results, int64_t& total,  const int64_t& creator_id, int32_t offset, int32_t limit, chen::IDB::ptr conn) {
    std::string countSql = "select count(*) from requirement where creator_id = ?";
    auto countStmt = conn->prepare(countSql);
    if (!countStmt) {
        ERROR(logger) << "stmt=" << countSql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    countStmt->bindInt64(1, creator_id);
    auto countRt = countStmt->query();
    if (!countRt) {
        return countStmt->getErrno();
    }
    if (countRt->next()) {
        total = countRt->getInt64(0);
    }
    if (total == 0) {
        return 0;
    }
    std::string sql = "select id, org_id, title, description, priority, status, creator_id, assignee_id, iteration, category, source, deadline, is_deleted, create_time, update_time from requirement where creator_id = ? order by id desc limit ? offset ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, creator_id);
    stmt->bindInt32(2, limit);
    stmt->bindInt32(3, offset);
    auto rt = stmt->query();
    if (!rt) {
        return 0;
    }
    while (rt->next()) {
        RequirementInfo::ptr v(new RequirementInfo);
        v->m_id = rt->getInt64(0);
        v->m_orgId = rt->getInt64(1);
        v->m_title = rt->getString(2);
        v->m_description = rt->getString(3);
        v->m_priority = rt->getInt32(4);
        v->m_status = rt->getInt32(5);
        v->m_creatorId = rt->getInt64(6);
        v->m_assigneeId = rt->getInt64(7);
        v->m_iteration = rt->getString(8);
        v->m_category = rt->getString(9);
        v->m_source = rt->getString(10);
        v->m_deadline = rt->getTime(11);
        v->m_isDeleted = rt->getInt32(12);
        v->m_createTime = rt->getTime(13);
        v->m_updateTime = rt->getTime(14);
        results.push_back(v);
    };
    return 0;
}

int RequirementInfoDao::QueryByAssigneeId(std::vector<RequirementInfo::ptr>& results,  const int64_t& assignee_id, chen::IDB::ptr conn) {
    std::string sql = "select id, org_id, title, description, priority, status, creator_id, assignee_id, iteration, category, source, deadline, is_deleted, create_time, update_time from requirement where assignee_id = ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, assignee_id);
    auto rt = stmt->query();
    if(!rt) {
        return 0;
    }
    while (rt->next()) {
        RequirementInfo::ptr v(new RequirementInfo);
        v->m_id = rt->getInt64(0);
        v->m_orgId = rt->getInt64(1);
        v->m_title = rt->getString(2);
        v->m_description = rt->getString(3);
        v->m_priority = rt->getInt32(4);
        v->m_status = rt->getInt32(5);
        v->m_creatorId = rt->getInt64(6);
        v->m_assigneeId = rt->getInt64(7);
        v->m_iteration = rt->getString(8);
        v->m_category = rt->getString(9);
        v->m_source = rt->getString(10);
        v->m_deadline = rt->getTime(11);
        v->m_isDeleted = rt->getInt32(12);
        v->m_createTime = rt->getTime(13);
        v->m_updateTime = rt->getTime(14);
        results.push_back(v);
    };
    return 0;
}

int RequirementInfoDao::QueryByAssigneeIdPages(std::vector<RequirementInfo::ptr>& results, int64_t& total,  const int64_t& assignee_id, int32_t offset, int32_t limit, chen::IDB::ptr conn) {
    std::string countSql = "select count(*) from requirement where assignee_id = ?";
    auto countStmt = conn->prepare(countSql);
    if (!countStmt) {
        ERROR(logger) << "stmt=" << countSql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    countStmt->bindInt64(1, assignee_id);
    auto countRt = countStmt->query();
    if (!countRt) {
        return countStmt->getErrno();
    }
    if (countRt->next()) {
        total = countRt->getInt64(0);
    }
    if (total == 0) {
        return 0;
    }
    std::string sql = "select id, org_id, title, description, priority, status, creator_id, assignee_id, iteration, category, source, deadline, is_deleted, create_time, update_time from requirement where assignee_id = ? order by id desc limit ? offset ?";
    auto stmt = conn->prepare(sql);
    if(!stmt) {
        ERROR(logger) << "stmt=" << sql
                 << " errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    stmt->bindInt64(1, assignee_id);
    stmt->bindInt32(2, limit);
    stmt->bindInt32(3, offset);
    auto rt = stmt->query();
    if (!rt) {
        return 0;
    }
    while (rt->next()) {
        RequirementInfo::ptr v(new RequirementInfo);
        v->m_id = rt->getInt64(0);
        v->m_orgId = rt->getInt64(1);
        v->m_title = rt->getString(2);
        v->m_description = rt->getString(3);
        v->m_priority = rt->getInt32(4);
        v->m_status = rt->getInt32(5);
        v->m_creatorId = rt->getInt64(6);
        v->m_assigneeId = rt->getInt64(7);
        v->m_iteration = rt->getString(8);
        v->m_category = rt->getString(9);
        v->m_source = rt->getString(10);
        v->m_deadline = rt->getTime(11);
        v->m_isDeleted = rt->getInt32(12);
        v->m_createTime = rt->getTime(13);
        v->m_updateTime = rt->getTime(14);
        results.push_back(v);
    };
    return 0;
}

int RequirementInfoDao::CreateTableSQLite3(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS requirement("
            "id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "org_id INTEGER NOT NULL DEFAULT 0,"
            "title TEXT NOT NULL DEFAULT '',"
            "description TEXT NOT NULL DEFAULT '',"
            "priority INTEGER NOT NULL DEFAULT 1,"
            "status INTEGER NOT NULL DEFAULT 0,"
            "creator_id INTEGER NOT NULL DEFAULT 0,"
            "assignee_id INTEGER NOT NULL DEFAULT 0,"
            "iteration TEXT NOT NULL DEFAULT '',"
            "category TEXT NOT NULL DEFAULT '',"
            "source TEXT NOT NULL DEFAULT '',"
            "deadline TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00',"
            "is_deleted INTEGER NOT NULL DEFAULT 0,"
            "create_time TIMESTAMP NOT NULL DEFAULT current_timestamp,"
            "update_time TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00');"
            "CREATE INDEX IF NOT EXISTS requirement_org_id ON requirement(org_id);"
            "CREATE INDEX IF NOT EXISTS requirement_creator_id ON requirement(creator_id);"
            "CREATE INDEX IF NOT EXISTS requirement_assignee_id ON requirement(assignee_id);"
            );
}

int RequirementInfoDao::CreateTableMySQL(chen::IDB::ptr conn) {
    return conn->execute("CREATE TABLE IF NOT EXISTS requirement("
            "`id` bigint AUTO_INCREMENT COMMENT '需求ID',"
            "`org_id` bigint NOT NULL DEFAULT 0 COMMENT '组织ID',"
            "`title` varchar(256) NOT NULL DEFAULT '' COMMENT '需求标题',"
            "`description` varchar(2048) NOT NULL DEFAULT '' COMMENT '需求描述',"
            "`priority` int NOT NULL DEFAULT 1 COMMENT '优先级: 1低 2中 3高 4紧急',"
            "`status` int NOT NULL DEFAULT 0 COMMENT '状态: 0草稿 1待处理 2进行中 3已完成 4已关闭',"
            "`creator_id` bigint NOT NULL DEFAULT 0 COMMENT '创建者ID',"
            "`assignee_id` bigint NOT NULL DEFAULT 0 COMMENT '负责人ID',"
            "`iteration` varchar(128) NOT NULL DEFAULT '' COMMENT '迭代',"
            "`category` varchar(128) NOT NULL DEFAULT '' COMMENT '分类',"
            "`source` varchar(128) NOT NULL DEFAULT '' COMMENT '需求来源',"
            "`deadline` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '截止时间',"
            "`is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除',"
            "`create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间',"
            "`update_time` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' ON UPDATE current_timestamp  COMMENT '更新时间',"
            "PRIMARY KEY(`id`),"
            "KEY `requirement_org_id` (`org_id`),"
            "KEY `requirement_creator_id` (`creator_id`),"
            "KEY `requirement_assignee_id` (`assignee_id`)) COMMENT='需求表'");
}

int RequirementInfoDao::MigrateTableSQLite3(chen::IDB::ptr conn) {
    auto data = conn->query("PRAGMA table_info(requirement)");
    if (!data) {
        ERROR(logger) << "PRAGMA table_info(requirement) errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(1)] = data->getString(2);
    }

    bool need_recreate = false;
    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: requirement.id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("org_id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: requirement.org_id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("title");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: requirement.title " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("description");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: requirement.description " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("priority");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: requirement.priority " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("status");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: requirement.status " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("creator_id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: requirement.creator_id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("assignee_id");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: requirement.assignee_id " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("iteration");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: requirement.iteration " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("category");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: requirement.category " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("source");
        if (it != existing_cols.end() && it->second != "TEXT") {
            INFO(logger) << "Column type changed: requirement.source " << it->second << " -> TEXT";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("deadline");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: requirement.deadline " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("is_deleted");
        if (it != existing_cols.end() && it->second != "INTEGER") {
            INFO(logger) << "Column type changed: requirement.is_deleted " << it->second << " -> INTEGER";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("create_time");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: requirement.create_time " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    {
        auto it = existing_cols.find("update_time");
        if (it != existing_cols.end() && it->second != "TIMESTAMP") {
            INFO(logger) << "Column type changed: requirement.update_time " << it->second << " -> TIMESTAMP";
            need_recreate = true;
        }
    }
    if (!need_recreate) {
        for (auto& [name, _] : existing_cols) {
            (void)_;  // suppress unused warning
            bool found = false;
            if (name == "id") found = true;
            if (name == "org_id") found = true;
            if (name == "title") found = true;
            if (name == "description") found = true;
            if (name == "priority") found = true;
            if (name == "status") found = true;
            if (name == "creator_id") found = true;
            if (name == "assignee_id") found = true;
            if (name == "iteration") found = true;
            if (name == "category") found = true;
            if (name == "source") found = true;
            if (name == "deadline") found = true;
            if (name == "is_deleted") found = true;
            if (name == "create_time") found = true;
            if (name == "update_time") found = true;
            if (!found) {
                need_recreate = true;
                WARN(logger) << "Column requirement." << name << " removed, table recreate required";
                break;
            }
        }
    }

    if (need_recreate) {
        INFO(logger) << "Recreating table requirement";

        std::vector<std::string> common_cols;
        if (existing_cols.find("id") != existing_cols.end()) {
            common_cols.push_back("id");
        }
        if (existing_cols.find("org_id") != existing_cols.end()) {
            common_cols.push_back("org_id");
        }
        if (existing_cols.find("title") != existing_cols.end()) {
            common_cols.push_back("title");
        }
        if (existing_cols.find("description") != existing_cols.end()) {
            common_cols.push_back("description");
        }
        if (existing_cols.find("priority") != existing_cols.end()) {
            common_cols.push_back("priority");
        }
        if (existing_cols.find("status") != existing_cols.end()) {
            common_cols.push_back("status");
        }
        if (existing_cols.find("creator_id") != existing_cols.end()) {
            common_cols.push_back("creator_id");
        }
        if (existing_cols.find("assignee_id") != existing_cols.end()) {
            common_cols.push_back("assignee_id");
        }
        if (existing_cols.find("iteration") != existing_cols.end()) {
            common_cols.push_back("iteration");
        }
        if (existing_cols.find("category") != existing_cols.end()) {
            common_cols.push_back("category");
        }
        if (existing_cols.find("source") != existing_cols.end()) {
            common_cols.push_back("source");
        }
        if (existing_cols.find("deadline") != existing_cols.end()) {
            common_cols.push_back("deadline");
        }
        if (existing_cols.find("is_deleted") != existing_cols.end()) {
            common_cols.push_back("is_deleted");
        }
        if (existing_cols.find("create_time") != existing_cols.end()) {
            common_cols.push_back("create_time");
        }
        if (existing_cols.find("update_time") != existing_cols.end()) {
            common_cols.push_back("update_time");
        }

        if (conn->execute("ALTER TABLE requirement RENAME TO requirement_tmp")) {
            ERROR(logger) << "RENAME TABLE requirement failed";
            return conn->getErrno();
        }
        CreateTableSQLite3(conn);
        if (!common_cols.empty()) {
            std::string cols;
            for (size_t i = 0; i < common_cols.size(); ++i) {
                if (i) cols += ",";
                cols += common_cols[i];
            }
            std::string sql = "INSERT INTO requirement (" + cols + ") SELECT " + cols + " FROM requirement_tmp";
            if (int rt = conn->execute(sql)) {
                ERROR(logger) << "copy data from requirement_tmp to requirement failed, errno=" << rt;
                // don't return; try to continue
            }
        }
        conn->execute("DROP TABLE requirement_tmp");
        return 0;
    }

    if (existing_cols.find("org_id") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.org_id";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN org_id INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN org_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("title") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.title";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN title TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN title failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("description") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.description";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN description TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN description failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("priority") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.priority";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN priority INTEGER NOT NULL DEFAULT 1");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN priority failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("status") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.status";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN status INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("creator_id") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.creator_id";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN creator_id INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN creator_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("assignee_id") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.assignee_id";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN assignee_id INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN assignee_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("iteration") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.iteration";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN iteration TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN iteration failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("category") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.category";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN category TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN category failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("source") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.source";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN source TEXT NOT NULL DEFAULT ''");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN source failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("deadline") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.deadline";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN deadline TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN deadline failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("is_deleted") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.is_deleted";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT 0");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN is_deleted failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("create_time") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.create_time";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN create_time TIMESTAMP NOT NULL DEFAULT current_timestamp");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("update_time") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.update_time";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN update_time TIMESTAMP NOT NULL DEFAULT '1980-01-01 00:00:00'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}

int RequirementInfoDao::MigrateTableMySQL(chen::IDB::ptr conn) {
    auto data = conn->query("SHOW COLUMNS FROM requirement");
    if (!data) {
        ERROR(logger) << "SHOW COLUMNS FROM requirement errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        return conn->getErrno();
    }
    std::map<std::string, std::string> existing_cols;  // name -> type
    while (data->next()) {
        existing_cols[data->getString(0)] = data->getString(1);
    }

    {
        auto it = existing_cols.find("id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column requirement.id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `id` bigint NOT NULL DEFAULT 0 COMMENT '需求ID'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("org_id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column requirement.org_id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `org_id` bigint NOT NULL DEFAULT 0 COMMENT '组织ID'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.org_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("title");
        if (it != existing_cols.end() && it->second != "varchar(256)") {
            INFO(logger) << "Modifying column requirement.title " << it->second << " -> varchar(256)";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `title` varchar(256) NOT NULL DEFAULT '' COMMENT '需求标题'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.title failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("description");
        if (it != existing_cols.end() && it->second != "varchar(2048)") {
            INFO(logger) << "Modifying column requirement.description " << it->second << " -> varchar(2048)";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `description` varchar(2048) NOT NULL DEFAULT '' COMMENT '需求描述'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.description failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("priority");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column requirement.priority " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `priority` int NOT NULL DEFAULT 1 COMMENT '优先级: 1低 2中 3高 4紧急'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.priority failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("status");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column requirement.status " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `status` int NOT NULL DEFAULT 0 COMMENT '状态: 0草稿 1待处理 2进行中 3已完成 4已关闭'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("creator_id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column requirement.creator_id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `creator_id` bigint NOT NULL DEFAULT 0 COMMENT '创建者ID'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.creator_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("assignee_id");
        if (it != existing_cols.end() && it->second != "bigint") {
            INFO(logger) << "Modifying column requirement.assignee_id " << it->second << " -> bigint";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `assignee_id` bigint NOT NULL DEFAULT 0 COMMENT '负责人ID'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.assignee_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("iteration");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column requirement.iteration " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `iteration` varchar(128) NOT NULL DEFAULT '' COMMENT '迭代'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.iteration failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("category");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column requirement.category " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `category` varchar(128) NOT NULL DEFAULT '' COMMENT '分类'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.category failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("source");
        if (it != existing_cols.end() && it->second != "varchar(128)") {
            INFO(logger) << "Modifying column requirement.source " << it->second << " -> varchar(128)";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `source` varchar(128) NOT NULL DEFAULT '' COMMENT '需求来源'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.source failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("deadline");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column requirement.deadline " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `deadline` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '截止时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.deadline failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("is_deleted");
        if (it != existing_cols.end() && it->second != "int") {
            INFO(logger) << "Modifying column requirement.is_deleted " << it->second << " -> int";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.is_deleted failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("create_time");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column requirement.create_time " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }
    {
        auto it = existing_cols.find("update_time");
        if (it != existing_cols.end() && it->second != "timestamp") {
            INFO(logger) << "Modifying column requirement.update_time " << it->second << " -> timestamp";
            int rt = conn->execute("ALTER TABLE requirement MODIFY COLUMN `update_time` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '更新时间'");
            if (rt) {
                ERROR(logger) << "MODIFY COLUMN requirement.update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    for (auto& [name, _] : existing_cols) {
        (void)_;
        bool found = false;
        if (name == "id") found = true;
        if (name == "org_id") found = true;
        if (name == "title") found = true;
        if (name == "description") found = true;
        if (name == "priority") found = true;
        if (name == "status") found = true;
        if (name == "creator_id") found = true;
        if (name == "assignee_id") found = true;
        if (name == "iteration") found = true;
        if (name == "category") found = true;
        if (name == "source") found = true;
        if (name == "deadline") found = true;
        if (name == "is_deleted") found = true;
        if (name == "create_time") found = true;
        if (name == "update_time") found = true;
        if (!found) {
            WARN(logger) << "Dropping column requirement." << name << " (not in schema, data will be lost)";
            int rt = conn->execute("ALTER TABLE requirement DROP COLUMN `" + name + "`");
            if (rt) {
                ERROR(logger) << "DROP COLUMN requirement." << name << " failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
            }
        }
    }

    if (existing_cols.find("org_id") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.org_id";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `org_id` bigint NOT NULL DEFAULT 0 COMMENT '组织ID'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN org_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("title") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.title";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `title` varchar(256) NOT NULL DEFAULT '' COMMENT '需求标题'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN title failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("description") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.description";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `description` varchar(2048) NOT NULL DEFAULT '' COMMENT '需求描述'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN description failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("priority") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.priority";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `priority` int NOT NULL DEFAULT 1 COMMENT '优先级: 1低 2中 3高 4紧急'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN priority failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("status") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.status";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `status` int NOT NULL DEFAULT 0 COMMENT '状态: 0草稿 1待处理 2进行中 3已完成 4已关闭'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN status failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("creator_id") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.creator_id";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `creator_id` bigint NOT NULL DEFAULT 0 COMMENT '创建者ID'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN creator_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("assignee_id") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.assignee_id";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `assignee_id` bigint NOT NULL DEFAULT 0 COMMENT '负责人ID'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN assignee_id failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("iteration") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.iteration";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `iteration` varchar(128) NOT NULL DEFAULT '' COMMENT '迭代'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN iteration failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("category") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.category";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `category` varchar(128) NOT NULL DEFAULT '' COMMENT '分类'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN category failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("source") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.source";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `source` varchar(128) NOT NULL DEFAULT '' COMMENT '需求来源'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN source failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("deadline") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.deadline";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `deadline` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '截止时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN deadline failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("is_deleted") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.is_deleted";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `is_deleted` int NOT NULL DEFAULT 0 COMMENT '是否删除'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN is_deleted failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("create_time") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.create_time";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `create_time` timestamp NOT NULL DEFAULT current_timestamp COMMENT '创建时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN create_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    if (existing_cols.find("update_time") == existing_cols.end()) {
        INFO(logger) << "Adding column requirement.update_time";
        int rt = conn->execute("ALTER TABLE requirement ADD COLUMN `update_time` timestamp NOT NULL DEFAULT '1980-01-01 00:00:00' COMMENT '更新时间'");
        if (rt) {
            ERROR(logger) << "ALTER TABLE requirement ADD COLUMN update_time failed, errno=" << conn->getErrno() << " errstr=" << conn->getErrStr();
        }
    }

    return 0;
}


} //namespace data
} //namespace blog
