/**
 * @file system_settings_info.h
 * @brief 系统设置表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#pragma once

#include <vector>

#include <chen/db/db.h>
#include <chen/db/query_builder.h>
#include <chen/util/util.h>

namespace blog {
namespace data {

class SystemSettingsInfoDao;
/**
 * @brief 系统设置表
 */
class SystemSettingsInfo {
friend class SystemSettingsInfoDao;
public:
    typedef std::shared_ptr<SystemSettingsInfo> ptr;

    SystemSettingsInfo();

    /**
     * @brief 获取主键id
     * @return 主键id
     */
    const int64_t& getId() { return m_id; }
    /**
     * @brief 设置主键id
     * @param v 主键id
     */
    void setId(const int64_t& v);

    /**
     * @brief 获取站点名称
     * @return 站点名称
     */
    const std::string& getSiteName() { return m_siteName; }
    /**
     * @brief 设置站点名称
     * @param v 站点名称
     */
    void setSiteName(const std::string& v);

    /**
     * @brief 获取站点描述
     * @return 站点描述
     */
    const std::string& getSiteDescription() { return m_siteDescription; }
    /**
     * @brief 设置站点描述
     * @param v 站点描述
     */
    void setSiteDescription(const std::string& v);

    /**
     * @brief 获取站点关键词
     * @return 站点关键词
     */
    const std::string& getSiteKeywords() { return m_siteKeywords; }
    /**
     * @brief 设置站点关键词
     * @param v 站点关键词
     */
    void setSiteKeywords(const std::string& v);

    /**
     * @brief 获取站点图标URL
     * @return 站点图标URL
     */
    const std::string& getSiteIcon() { return m_siteIcon; }
    /**
     * @brief 设置站点图标URL
     * @param v 站点图标URL
     */
    void setSiteIcon(const std::string& v);

    /**
     * @brief 获取站点Logo URL
     * @return 站点Logo URL
     */
    const std::string& getSiteLogo() { return m_siteLogo; }
    /**
     * @brief 设置站点Logo URL
     * @param v 站点Logo URL
     */
    void setSiteLogo(const std::string& v);

    /**
     * @brief 获取Favicon URL
     * @return Favicon URL
     */
    const std::string& getFavicon() { return m_favicon; }
    /**
     * @brief 设置Favicon URL
     * @param v Favicon URL
     */
    void setFavicon(const std::string& v);

    /**
     * @brief 获取管理员邮箱
     * @return 管理员邮箱
     */
    const std::string& getAdminEmail() { return m_adminEmail; }
    /**
     * @brief 设置管理员邮箱
     * @param v 管理员邮箱
     */
    void setAdminEmail(const std::string& v);

    /**
     * @brief 获取时区
     * @return 时区
     */
    const std::string& getTimezone() { return m_timezone; }
    /**
     * @brief 设置时区
     * @param v 时区
     */
    void setTimezone(const std::string& v);

    /**
     * @brief 获取语言
     * @return 语言
     */
    const std::string& getLanguage() { return m_language; }
    /**
     * @brief 设置语言
     * @param v 语言
     */
    void setLanguage(const std::string& v);

    /**
     * @brief 获取SMTP主机
     * @return SMTP主机
     */
    const std::string& getSmtpHost() { return m_smtpHost; }
    /**
     * @brief 设置SMTP主机
     * @param v SMTP主机
     */
    void setSmtpHost(const std::string& v);

    /**
     * @brief 获取SMTP端口
     * @return SMTP端口
     */
    const int32_t& getSmtpPort() { return m_smtpPort; }
    /**
     * @brief 设置SMTP端口
     * @param v SMTP端口
     */
    void setSmtpPort(const int32_t& v);

    /**
     * @brief 获取SMTP用户名
     * @return SMTP用户名
     */
    const std::string& getSmtpUsername() { return m_smtpUsername; }
    /**
     * @brief 设置SMTP用户名
     * @param v SMTP用户名
     */
    void setSmtpUsername(const std::string& v);

    /**
     * @brief 获取SMTP密码
     * @return SMTP密码
     */
    const std::string& getSmtpPassword() { return m_smtpPassword; }
    /**
     * @brief 设置SMTP密码
     * @param v SMTP密码
     */
    void setSmtpPassword(const std::string& v);

    /**
     * @brief 获取SMTP加密方式: none/ssl/tls
     * @return SMTP加密方式: none/ssl/tls
     */
    const std::string& getSmtpEncryption() { return m_smtpEncryption; }
    /**
     * @brief 设置SMTP加密方式: none/ssl/tls
     * @param v SMTP加密方式: none/ssl/tls
     */
    void setSmtpEncryption(const std::string& v);

    /**
     * @brief 获取发件人邮箱
     * @return 发件人邮箱
     */
    const std::string& getFromEmail() { return m_fromEmail; }
    /**
     * @brief 设置发件人邮箱
     * @param v 发件人邮箱
     */
    void setFromEmail(const std::string& v);

    /**
     * @brief 获取发件人名称
     * @return 发件人名称
     */
    const std::string& getFromName() { return m_fromName; }
    /**
     * @brief 设置发件人名称
     * @param v 发件人名称
     */
    void setFromName(const std::string& v);

    /**
     * @brief 获取回复邮箱
     * @return 回复邮箱
     */
    const std::string& getReplyTo() { return m_replyTo; }
    /**
     * @brief 设置回复邮箱
     * @param v 回复邮箱
     */
    void setReplyTo(const std::string& v);

    /**
     * @brief 获取是否允许注册
     * @return 是否允许注册
     */
    const int32_t& getEnableRegistration() { return m_enableRegistration; }
    /**
     * @brief 设置是否允许注册
     * @param v 是否允许注册
     */
    void setEnableRegistration(const int32_t& v);

    /**
     * @brief 获取是否需要邮箱验证
     * @return 是否需要邮箱验证
     */
    const int32_t& getRequireEmailVerification() { return m_requireEmailVerification; }
    /**
     * @brief 设置是否需要邮箱验证
     * @param v 是否需要邮箱验证
     */
    void setRequireEmailVerification(const int32_t& v);

    /**
     * @brief 获取是否允许评论
     * @return 是否允许评论
     */
    const int32_t& getAllowComments() { return m_allowComments; }
    /**
     * @brief 设置是否允许评论
     * @param v 是否允许评论
     */
    void setAllowComments(const int32_t& v);

    /**
     * @brief 获取评论是否需要审核
     * @return 评论是否需要审核
     */
    const int32_t& getModerateComments() { return m_moderateComments; }
    /**
     * @brief 设置评论是否需要审核
     * @param v 评论是否需要审核
     */
    void setModerateComments(const int32_t& v);

    /**
     * @brief 获取最大上传文件大小(MB)
     * @return 最大上传文件大小(MB)
     */
    const int32_t& getMaxFileSize() { return m_maxFileSize; }
    /**
     * @brief 设置最大上传文件大小(MB)
     * @param v 最大上传文件大小(MB)
     */
    void setMaxFileSize(const int32_t& v);

    /**
     * @brief 获取允许上传的文件类型
     * @return 允许上传的文件类型
     */
    const std::string& getAllowedFileTypes() { return m_allowedFileTypes; }
    /**
     * @brief 设置允许上传的文件类型
     * @param v 允许上传的文件类型
     */
    void setAllowedFileTypes(const std::string& v);

    /**
     * @brief 获取会话超时时间(小时)
     * @return 会话超时时间(小时)
     */
    const int32_t& getSessionTimeout() { return m_sessionTimeout; }
    /**
     * @brief 设置会话超时时间(小时)
     * @param v 会话超时时间(小时)
     */
    void setSessionTimeout(const int32_t& v);

    /**
     * @brief 获取是否维护模式
     * @return 是否维护模式
     */
    const int32_t& getMaintenanceMode() { return m_maintenanceMode; }
    /**
     * @brief 设置是否维护模式
     * @param v 是否维护模式
     */
    void setMaintenanceMode(const int32_t& v);

    /**
     * @brief 获取备份计划: disabled/daily/weekly/monthly
     * @return 备份计划: disabled/daily/weekly/monthly
     */
    const std::string& getBackupSchedule() { return m_backupSchedule; }
    /**
     * @brief 设置备份计划: disabled/daily/weekly/monthly
     * @param v 备份计划: disabled/daily/weekly/monthly
     */
    void setBackupSchedule(const std::string& v);

    /**
     * @brief 获取创建时间
     * @return 创建时间
     */
    const int64_t& getCreatedAt() { return m_createdAt; }
    /**
     * @brief 设置创建时间
     * @param v 创建时间
     */
    void setCreatedAt(const int64_t& v);

    /**
     * @brief 获取更新时间
     * @return 更新时间
     */
    const int64_t& getUpdatedAt() { return m_updatedAt; }
    /**
     * @brief 设置更新时间
     * @param v 更新时间
     */
    void setUpdatedAt(const int64_t& v);

    /**
     * @brief 转为 JSON 字符串
     * @return JSON 字符串
     */
    std::string toJsonString() const;

    /** @brief 清除脏标记（Update 成功后自动调用） */
    void markClean() { m_flags = 0; }
    /**
     * @brief 是否有字段被修改过
     * @return true 有未保存的修改，false 无修改
     */
    bool isDirty() const { return m_flags != 0; }

private:
    int32_t m_smtpPort;
    int32_t m_enableRegistration;
    int32_t m_requireEmailVerification;
    int32_t m_allowComments;
    int32_t m_moderateComments;
    int32_t m_maxFileSize;
    int32_t m_sessionTimeout;
    int32_t m_maintenanceMode;
    int64_t m_id;
    std::string m_siteName;
    std::string m_siteDescription;
    std::string m_siteKeywords;
    std::string m_siteIcon;
    std::string m_siteLogo;
    std::string m_favicon;
    std::string m_adminEmail;
    std::string m_timezone;
    std::string m_language;
    std::string m_smtpHost;
    std::string m_smtpUsername;
    std::string m_smtpPassword;
    std::string m_smtpEncryption;
    std::string m_fromEmail;
    std::string m_fromName;
    std::string m_replyTo;
    std::string m_allowedFileTypes;
    std::string m_backupSchedule;
    int64_t m_createdAt;
    int64_t m_updatedAt;
    uint64_t m_flags = 0;
};


class SystemSettingsInfoDao {
public:
    typedef std::shared_ptr<SystemSettingsInfoDao> ptr;
    static int Update(SystemSettingsInfo::ptr info, chen::IDB::ptr conn);
    static int Insert(SystemSettingsInfo::ptr info, chen::IDB::ptr conn);
    static int InsertOrUpdate(SystemSettingsInfo::ptr info, chen::IDB::ptr conn);
    static int BatchInsert(const std::vector<SystemSettingsInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchUpdate(const std::vector<SystemSettingsInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchDelete(const std::vector<int64_t>& ids, chen::IDB::ptr conn);
    static int Delete(SystemSettingsInfo::ptr info, chen::IDB::ptr conn);
    static int Delete(const int64_t& id, chen::IDB::ptr conn);
    static int DeleteById( const int64_t& id, chen::IDB::ptr conn);
    static int QueryAll(std::vector<SystemSettingsInfo::ptr>& results, chen::IDB::ptr conn);
    static SystemSettingsInfo::ptr Query( const int64_t& id, chen::IDB::ptr conn);
    static int CreateTableSQLite3(chen::IDB::ptr info);
    static int CreateTableMySQL(chen::IDB::ptr info);
    static int MigrateTableSQLite3(chen::IDB::ptr info);
    static int MigrateTableMySQL(chen::IDB::ptr info);
    static int Migrate(chen::IDB::ptr conn);
    static SystemSettingsInfo::ptr ParseRow(chen::ISQLData::ptr data);
    static int QueryByBuilder(std::vector<SystemSettingsInfo::ptr>& results, chen::QueryBuilder::ptr qb, chen::IDB::ptr conn);
    static int QueryByBuilderPages(std::vector<SystemSettingsInfo::ptr>& results, int64_t& total, chen::QueryBuilder::ptr qb, int32_t offset, int32_t limit, chen::IDB::ptr conn);
};

} //namespace data
} //namespace blog
