/**
 * @file task_info.h
 * @brief 任务表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#pragma once

#include <vector>

#include <chen/db/db.h>
#include <chen/db/query_builder.h>
#include <chen/util/util.h>

namespace blog {
namespace data {

class TaskInfoDao;
/**
 * @brief 任务表
 */
class TaskInfo {
friend class TaskInfoDao;
public:
    typedef std::shared_ptr<TaskInfo> ptr;

    TaskInfo();

    /**
     * @brief 获取任务ID
     * @return 任务ID
     */
    const int64_t& getId() { return m_id; }
    /**
     * @brief 设置任务ID
     * @param v 任务ID
     */
    void setId(const int64_t& v);

    /**
     * @brief 获取组织ID
     * @return 组织ID
     */
    const int64_t& getOrgId() { return m_orgId; }
    /**
     * @brief 设置组织ID
     * @param v 组织ID
     */
    void setOrgId(const int64_t& v);

    /**
     * @brief 获取任务标题
     * @return 任务标题
     */
    const std::string& getTitle() { return m_title; }
    /**
     * @brief 设置任务标题
     * @param v 任务标题
     */
    void setTitle(const std::string& v);

    /**
     * @brief 获取任务描述
     * @return 任务描述
     */
    const std::string& getDescription() { return m_description; }
    /**
     * @brief 设置任务描述
     * @param v 任务描述
     */
    void setDescription(const std::string& v);

    /**
     * @brief 获取优先级: 1低 2中 3高 4紧急
     * @return 优先级: 1低 2中 3高 4紧急
     */
    const int32_t& getPriority() { return m_priority; }
    /**
     * @brief 设置优先级: 1低 2中 3高 4紧急
     * @param v 优先级: 1低 2中 3高 4紧急
     */
    void setPriority(const int32_t& v);

    /**
     * @brief 获取状态: 0待办 1进行中 2已完成 3已关闭
     * @return 状态: 0待办 1进行中 2已完成 3已关闭
     */
    const int32_t& getStatus() { return m_status; }
    /**
     * @brief 设置状态: 0待办 1进行中 2已完成 3已关闭
     * @param v 状态: 0待办 1进行中 2已完成 3已关闭
     */
    void setStatus(const int32_t& v);

    /**
     * @brief 获取创建者ID
     * @return 创建者ID
     */
    const int64_t& getCreatorId() { return m_creatorId; }
    /**
     * @brief 设置创建者ID
     * @param v 创建者ID
     */
    void setCreatorId(const int64_t& v);

    /**
     * @brief 获取负责人ID
     * @return 负责人ID
     */
    const int64_t& getAssigneeId() { return m_assigneeId; }
    /**
     * @brief 设置负责人ID
     * @param v 负责人ID
     */
    void setAssigneeId(const int64_t& v);

    /**
     * @brief 获取关联需求ID
     * @return 关联需求ID
     */
    const int64_t& getRequirementId() { return m_requirementId; }
    /**
     * @brief 设置关联需求ID
     * @param v 关联需求ID
     */
    void setRequirementId(const int64_t& v);

    /**
     * @brief 获取关联缺陷ID
     * @return 关联缺陷ID
     */
    const int64_t& getBugId() { return m_bugId; }
    /**
     * @brief 设置关联缺陷ID
     * @param v 关联缺陷ID
     */
    void setBugId(const int64_t& v);

    /**
     * @brief 获取截止时间
     * @return 截止时间
     */
    const int64_t& getDeadline() { return m_deadline; }
    /**
     * @brief 设置截止时间
     * @param v 截止时间
     */
    void setDeadline(const int64_t& v);

    /**
     * @brief 获取预估工时(小时)
     * @return 预估工时(小时)
     */
    const int32_t& getEstimatedHours() { return m_estimatedHours; }
    /**
     * @brief 设置预估工时(小时)
     * @param v 预估工时(小时)
     */
    void setEstimatedHours(const int32_t& v);

    /**
     * @brief 获取是否删除
     * @return 是否删除
     */
    const int32_t& getIsDeleted() { return m_isDeleted; }
    /**
     * @brief 设置是否删除
     * @param v 是否删除
     */
    void setIsDeleted(const int32_t& v);

    /**
     * @brief 获取创建时间
     * @return 创建时间
     */
    const int64_t& getCreateTime() { return m_createTime; }
    /**
     * @brief 设置创建时间
     * @param v 创建时间
     */
    void setCreateTime(const int64_t& v);

    /**
     * @brief 获取更新时间
     * @return 更新时间
     */
    const int64_t& getUpdateTime() { return m_updateTime; }
    /**
     * @brief 设置更新时间
     * @param v 更新时间
     */
    void setUpdateTime(const int64_t& v);

    /**
     * @brief 转为 JSON 字符串
     * @return JSON 字符串
     */
    std::string toJsonString() const;

    /** @brief 清除脏标记（Update 成功后自动调用） */
    void markClean() { m_flags = 0; }
    /**
     * @brief 是否有字段被修改过
     * @return true 有未保存的修改，false 无修改
     */
    bool isDirty() const { return m_flags != 0; }

private:
    int32_t m_priority;
    int32_t m_status;
    int32_t m_estimatedHours;
    int32_t m_isDeleted;
    int64_t m_id;
    int64_t m_orgId;
    int64_t m_creatorId;
    int64_t m_assigneeId;
    int64_t m_requirementId;
    int64_t m_bugId;
    std::string m_title;
    std::string m_description;
    int64_t m_deadline;
    int64_t m_createTime;
    int64_t m_updateTime;
    uint64_t m_flags = 0;
};


class TaskInfoDao {
public:
    typedef std::shared_ptr<TaskInfoDao> ptr;
    static int Update(TaskInfo::ptr info, chen::IDB::ptr conn);
    static int Insert(TaskInfo::ptr info, chen::IDB::ptr conn);
    static int InsertOrUpdate(TaskInfo::ptr info, chen::IDB::ptr conn);
    static int BatchInsert(const std::vector<TaskInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchUpdate(const std::vector<TaskInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchDelete(const std::vector<int64_t>& ids, chen::IDB::ptr conn);
    static int Delete(TaskInfo::ptr info, chen::IDB::ptr conn);
    static int Delete(const int64_t& id, chen::IDB::ptr conn);
    static int DeleteById( const int64_t& id, chen::IDB::ptr conn);
    static int DeleteByOrgId( const int64_t& org_id, chen::IDB::ptr conn);
    static int DeleteByCreatorId( const int64_t& creator_id, chen::IDB::ptr conn);
    static int DeleteByAssigneeId( const int64_t& assignee_id, chen::IDB::ptr conn);
    static int QueryAll(std::vector<TaskInfo::ptr>& results, chen::IDB::ptr conn);
    static TaskInfo::ptr Query( const int64_t& id, chen::IDB::ptr conn);
    static int QueryByOrgId(std::vector<TaskInfo::ptr>& results,  const int64_t& org_id, chen::IDB::ptr conn);
    static int QueryByOrgIdPages(std::vector<TaskInfo::ptr>& results, int64_t& total,  const int64_t& org_id, int32_t offset, int32_t limit, chen::IDB::ptr conn);
    static int QueryByCreatorId(std::vector<TaskInfo::ptr>& results,  const int64_t& creator_id, chen::IDB::ptr conn);
    static int QueryByCreatorIdPages(std::vector<TaskInfo::ptr>& results, int64_t& total,  const int64_t& creator_id, int32_t offset, int32_t limit, chen::IDB::ptr conn);
    static int QueryByAssigneeId(std::vector<TaskInfo::ptr>& results,  const int64_t& assignee_id, chen::IDB::ptr conn);
    static int QueryByAssigneeIdPages(std::vector<TaskInfo::ptr>& results, int64_t& total,  const int64_t& assignee_id, int32_t offset, int32_t limit, chen::IDB::ptr conn);
    static int CreateTableSQLite3(chen::IDB::ptr info);
    static int CreateTableMySQL(chen::IDB::ptr info);
    static int MigrateTableSQLite3(chen::IDB::ptr info);
    static int MigrateTableMySQL(chen::IDB::ptr info);
    static int Migrate(chen::IDB::ptr conn);
    static TaskInfo::ptr ParseRow(chen::ISQLData::ptr data);
    static int QueryByBuilder(std::vector<TaskInfo::ptr>& results, chen::QueryBuilder::ptr qb, chen::IDB::ptr conn);
    static int QueryByBuilderPages(std::vector<TaskInfo::ptr>& results, int64_t& total, chen::QueryBuilder::ptr qb, int32_t offset, int32_t limit, chen::IDB::ptr conn);
};

} //namespace data
} //namespace blog
