/**
 * @file user_info.h
 * @brief 用户表
 * @note Auto-generated by ORM code generator. DO NOT MODIFY.
 */
#pragma once

#include <vector>

#include <chen/db/db.h>
#include <chen/db/query_builder.h>
#include <chen/util/util.h>

namespace blog {
namespace data {

class UserInfoDao;
/**
 * @brief 用户表
 */
class UserInfo {
friend class UserInfoDao;
public:
    typedef std::shared_ptr<UserInfo> ptr;

    UserInfo();

    /**
     * @brief 获取主键id
     * @return 主键id
     */
    const int64_t& getId() { return m_id; }
    /**
     * @brief 设置主键id
     * @param v 主键id
     */
    void setId(const int64_t& v);

    /**
     * @brief 获取用户名
     * @return 用户名
     */
    const std::string& getName() { return m_name; }
    /**
     * @brief 设置用户名
     * @param v 用户名
     */
    void setName(const std::string& v);

    /**
     * @brief 获取账户名称
     * @return 账户名称
     */
    const std::string& getAccount() { return m_account; }
    /**
     * @brief 设置账户名称
     * @param v 账户名称
     */
    void setAccount(const std::string& v);

    /**
     * @brief 获取头像地址
     * @return 头像地址
     */
    const std::string& getAvatar() { return m_avatar; }
    /**
     * @brief 设置头像地址
     * @param v 头像地址
     */
    void setAvatar(const std::string& v);

    /**
     * @brief 获取邮箱地址
     * @return 邮箱地址
     */
    const std::string& getEmail() { return m_email; }
    /**
     * @brief 设置邮箱地址
     * @param v 邮箱地址
     */
    void setEmail(const std::string& v);

    /**
     * @brief 获取角色: 1用户, 2管理员, 3编辑, 4审核员
     * @return 角色: 1用户, 2管理员, 3编辑, 4审核员
     */
    const int32_t& getRole() { return m_role; }
    /**
     * @brief 设置角色: 1用户, 2管理员, 3编辑, 4审核员
     * @param v 角色: 1用户, 2管理员, 3编辑, 4审核员
     */
    void setRole(const int32_t& v);

    /**
     * @brief 获取用户密码
     * @return 用户密码
     */
    const std::string& getPasswd() { return m_passwd; }
    /**
     * @brief 设置用户密码
     * @param v 用户密码
     */
    void setPasswd(const std::string& v);

    /**
     * @brief 获取账号状态
     * @return 账号状态
     */
    const int32_t& getState() { return m_state; }
    /**
     * @brief 设置账号状态
     * @param v 账号状态
     */
    void setState(const int32_t& v);

    /**
     * @brief 获取用户简介
     * @return 用户简介
     */
    const std::string& getBio() { return m_bio; }
    /**
     * @brief 设置用户简介
     * @param v 用户简介
     */
    void setBio(const std::string& v);

    /**
     * @brief 获取个人网站
     * @return 个人网站
     */
    const std::string& getWebsite() { return m_website; }
    /**
     * @brief 设置个人网站
     * @param v 个人网站
     */
    void setWebsite(const std::string& v);

    /**
     * @brief 获取GitHub地址
     * @return GitHub地址
     */
    const std::string& getGithub() { return m_github; }
    /**
     * @brief 设置GitHub地址
     * @param v GitHub地址
     */
    void setGithub(const std::string& v);

    /**
     * @brief 获取用户所在地
     * @return 用户所在地
     */
    const std::string& getLocation() { return m_location; }
    /**
     * @brief 设置用户所在地
     * @param v 用户所在地
     */
    void setLocation(const std::string& v);

    /**
     * @brief 获取登录凭证
     * @return 登录凭证
     */
    const std::string& getToken() { return m_token; }
    /**
     * @brief 设置登录凭证
     * @param v 登录凭证
     */
    void setToken(const std::string& v);

    /**
     * @brief 获取凭证过期时间
     * @return 凭证过期时间
     */
    const int64_t& getTokenTime() { return m_tokenTime; }
    /**
     * @brief 设置凭证过期时间
     * @param v 凭证过期时间
     */
    void setTokenTime(const int64_t& v);

    /**
     * @brief 获取上次登录时间
     * @return 上次登录时间
     */
    const int64_t& getLoginTime() { return m_loginTime; }
    /**
     * @brief 设置上次登录时间
     * @param v 上次登录时间
     */
    void setLoginTime(const int64_t& v);

    /**
     * @brief 获取账号是否已经删除
     * @return 账号是否已经删除
     */
    const int32_t& getIsDeleted() { return m_isDeleted; }
    /**
     * @brief 设置账号是否已经删除
     * @param v 账号是否已经删除
     */
    void setIsDeleted(const int32_t& v);

    /**
     * @brief 获取账号创建时间
     * @return 账号创建时间
     */
    const int64_t& getCreateTime() { return m_createTime; }
    /**
     * @brief 设置账号创建时间
     * @param v 账号创建时间
     */
    void setCreateTime(const int64_t& v);

    /**
     * @brief 获取账号信息上一次更新时间
     * @return 账号信息上一次更新时间
     */
    const int64_t& getUpdateTime() { return m_updateTime; }
    /**
     * @brief 设置账号信息上一次更新时间
     * @param v 账号信息上一次更新时间
     */
    void setUpdateTime(const int64_t& v);

    /**
     * @brief 转为 JSON 字符串
     * @return JSON 字符串
     */
    std::string toJsonString() const;

    /** @brief 清除脏标记（Update 成功后自动调用） */
    void markClean() { m_flags = 0; }
    /**
     * @brief 是否有字段被修改过
     * @return true 有未保存的修改，false 无修改
     */
    bool isDirty() const { return m_flags != 0; }

private:
    int32_t m_role;
    int32_t m_state;
    int32_t m_isDeleted;
    int64_t m_id;
    int64_t m_tokenTime;
    std::string m_name;
    std::string m_account;
    std::string m_avatar;
    std::string m_email;
    std::string m_passwd;
    std::string m_bio;
    std::string m_website;
    std::string m_github;
    std::string m_location;
    std::string m_token;
    int64_t m_loginTime;
    int64_t m_createTime;
    int64_t m_updateTime;
    uint64_t m_flags = 0;
};


class UserInfoDao {
public:
    typedef std::shared_ptr<UserInfoDao> ptr;
    static int Update(UserInfo::ptr info, chen::IDB::ptr conn);
    static int Insert(UserInfo::ptr info, chen::IDB::ptr conn);
    static int InsertOrUpdate(UserInfo::ptr info, chen::IDB::ptr conn);
    static int BatchInsert(const std::vector<UserInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchUpdate(const std::vector<UserInfo::ptr>& infos, chen::IDB::ptr conn);
    static int BatchDelete(const std::vector<int64_t>& ids, chen::IDB::ptr conn);
    static int Delete(UserInfo::ptr info, chen::IDB::ptr conn);
    static int Delete(const int64_t& id, chen::IDB::ptr conn);
    static int DeleteById( const int64_t& id, chen::IDB::ptr conn);
    static int DeleteByAccount( const std::string& account, chen::IDB::ptr conn);
    static int DeleteByEmail( const std::string& email, chen::IDB::ptr conn);
    static int DeleteByName( const std::string& name, chen::IDB::ptr conn);
    static int QueryAll(std::vector<UserInfo::ptr>& results, chen::IDB::ptr conn);
    static UserInfo::ptr Query( const int64_t& id, chen::IDB::ptr conn);
    static UserInfo::ptr QueryByAccount( const std::string& account, chen::IDB::ptr conn);
    static UserInfo::ptr QueryByEmail( const std::string& email, chen::IDB::ptr conn);
    static UserInfo::ptr QueryByName( const std::string& name, chen::IDB::ptr conn);
    static int CreateTableSQLite3(chen::IDB::ptr info);
    static int CreateTableMySQL(chen::IDB::ptr info);
    static int MigrateTableSQLite3(chen::IDB::ptr info);
    static int MigrateTableMySQL(chen::IDB::ptr info);
    static int Migrate(chen::IDB::ptr conn);
    static UserInfo::ptr ParseRow(chen::ISQLData::ptr data);
    static int QueryByBuilder(std::vector<UserInfo::ptr>& results, chen::QueryBuilder::ptr qb, chen::IDB::ptr conn);
    static int QueryByBuilderPages(std::vector<UserInfo::ptr>& results, int64_t& total, chen::QueryBuilder::ptr qb, int32_t offset, int32_t limit, chen::IDB::ptr conn);
};

} //namespace data
} //namespace blog
