#include "../manager/article_category_rel_manager.h"        // IWYU pragma: keep
#include "../manager/article_label_rel_manager.h"           // IWYU pragma: keep
#include "../manager/article_manager.h"                     // IWYU pragma: keep
#include "../manager/backup_record_manager.h"                // IWYU pragma: keep
#include "../manager/article_praise_rel_manager.h"          // IWYU pragma: keep
#include "../manager/assignment_manager.h"                  // IWYU pragma: keep
#include "../manager/assignment_organization_rel_manager.h" // IWYU pragma: keep
#include "../manager/assignment_user_rel_manager.h"         // IWYU pragma: keep
#include "../manager/bug_manager.h"                         // IWYU pragma: keep
#include "../manager/category_manager.h"                    // IWYU pragma: keep
#include "../manager/chunk_upload_manager.h"                // IWYU pragma: keep
#include "../manager/comment_manager.h"                     // IWYU pragma: keep
#include "../manager/error_code_manager.h"                  // IWYU pragma: keep
#include "../manager/export_record_manager.h"                // IWYU pragma: keep
#include "../manager/faq_manager.h"                          // IWYU pragma: keep
#include "../manager/feedback_manager.h"                     // IWYU pragma: keep
#include "../manager/comment_praise_rel_manager.h"          // IWYU pragma: keep
#include "../manager/label_manager.h"                       // IWYU pragma: keep
#include "../manager/notification_manager.h"                // IWYU pragma: keep
#include "../manager/organization_apply_manager.h"          // IWYU pragma: keep
#include "../manager/organization_manager.h"                // IWYU pragma: keep
#include "../manager/organization_repo_manager.h"           // IWYU pragma: keep
#include "../manager/organization_repo_pr_manager.h"        // IWYU pragma: keep
#include "../manager/organization_user_rel_manager.h"       // IWYU pragma: keep
#include "../manager/requirement_manager.h"                 // IWYU pragma: keep
#include "../manager/resource_manager.h"                    // IWYU pragma: keep
#include "../manager/system_settings_manager.h"             // IWYU pragma: keep
#include "../manager/task_manager.h"                        // IWYU pragma: keep
#include "../manager/user_ai_config_manager.h"              // IWYU pragma: keep
#include "../manager/user_follow_rel_manager.h"             // IWYU pragma: keep
#include "../manager/user_manager.h"                        // IWYU pragma: keep
