#include "../manager/article_category_rel_manager.h"        // IWYU pragma: keep
#include "../manager/article_label_rel_manager.h"           // IWYU pragma: keep
#include "../manager/article_manager.h"                     // IWYU pragma: keep
#include "../manager/assignment_manager.h"                  // IWYU pragma: keep
#include "../manager/assignment_organization_rel_manager.h" // IWYU pragma: keep
#include "../manager/assignment_user_rel_manager.h"         // IWYU pragma: keep
#include "../manager/category_manager.h"                    // IWYU pragma: keep
#include "../manager/chunk_upload_manager.h"                // IWYU pragma: keep
#include "../manager/notification_manager.h"               // IWYU pragma: keep
#include "../manager/label_manager.h"                       // IWYU pragma: keep
#include "../manager/organization_manager.h"                // IWYU pragma: keep
#include "../manager/organization_user_rel_manager.h"       // IWYU pragma: keep
#include "../manager/resource_manager.h"                    // IWYU pragma: keep
#include "../manager/user_manager.h"                        // IWYU pragma: keep
