#include "../servlets/article/admin_comment_approve_servlet.h"              // IWYU pragma: keep
#include "../servlets/article/admin_comment_delete_servlet.h"               // IWYU pragma: keep
#include "../servlets/article/admin_comment_list_servlet.h"                 // IWYU pragma: keep
#include "../servlets/article/admin_comment_reject_servlet.h"               // IWYU pragma: keep
#include "../servlets/article/admin_comment_spam_servlet.h"                 // IWYU pragma: keep
#include "../servlets/article/admin_comment_stats_servlet.h"                // IWYU pragma: keep
#include "../servlets/article/article_admin_lists_servlet.h"                // IWYU pragma: keep
#include "../servlets/article/article_admin_stats_servlet.h"                // IWYU pragma: keep
#include "../servlets/article/article_create_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/article_delete_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/article_detail_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/article_is_praising_servlet.h"                // IWYU pragma: keep
#include "../servlets/article/article_list_by_category_servlet.h"           // IWYU pragma: keep
#include "../servlets/article/article_list_by_label_servlet.h"              // IWYU pragma: keep
#include "../servlets/article/article_praise_list_servlet.h"                // IWYU pragma: keep
#include "../servlets/article/article_praise_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/article_publish_servlet.h"                    // IWYU pragma: keep
#include "../servlets/article/article_query_servlet.h"                      // IWYU pragma: keep
#include "../servlets/article/article_switch_state_servlet.h"               // IWYU pragma: keep
#include "../servlets/article/article_update_category_servlet.h"            // IWYU pragma: keep
#include "../servlets/article/article_update_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/article_verify_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/article_view_servlet.h"                       // IWYU pragma: keep
#include "../servlets/article/comment_create_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/comment_delete_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/comment_list_servlet.h"                       // IWYU pragma: keep
#include "../servlets/article/comment_praise_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/comment_replies_servlet.h"                    // IWYU pragma: keep
#include "../servlets/article/comment_update_servlet.h"                     // IWYU pragma: keep
#include "../servlets/assignment/assignment_admin_lists_servlet.h"          // IWYU pragma: keep
#include "../servlets/assignment/assignment_admin_stats_servlet.h"          // IWYU pragma: keep
#include "../servlets/assignment/assignment_create_servlet.h"               // IWYU pragma: keep
#include "../servlets/assignment/assignment_delete_servlet.h"               // IWYU pragma: keep
#include "../servlets/assignment/assignment_detail_servlet.h"               // IWYU pragma: keep
#include "../servlets/assignment/assignment_organization_create_servlet.h"  // IWYU pragma: keep
#include "../servlets/assignment/assignment_submission_list_servlet.h"      // IWYU pragma: keep
#include "../servlets/category/category_create_servlet.h"                   // IWYU pragma: keep
#include "../servlets/category/category_delete_servlet.h"                   // IWYU pragma: keep
#include "../servlets/category/category_query_servlet.h"                    // IWYU pragma: keep
#include "../servlets/dashboard/dashboard_activities_servlet.h"             // IWYU pragma: keep
#include "../servlets/dashboard/dashboard_recent_users_servlet.h"           // IWYU pragma: keep
#include "../servlets/dashboard/dashboard_stats_servlet.h"                  // IWYU pragma: keep
#include "../servlets/dashboard/dashboard_trend_servlet.h"                  // IWYU pragma: keep
#include "../servlets/file/chunk_upload_servlet.h"                          // IWYU pragma: keep
#include "../servlets/file/file_download_servlet.h"                         // IWYU pragma: keep
#include "../servlets/file/file_upload_servlet.h"                           // IWYU pragma: keep
#include "../servlets/label/label_create_servlet.h"                         // IWYU pragma: keep
#include "../servlets/label/label_delete_servlet.h"                         // IWYU pragma: keep
#include "../servlets/label/label_query_servlet.h"                          // IWYU pragma: keep
#include "../servlets/notify/notification_list_servlet.h"                   // IWYU pragma: keep
#include "../servlets/notify/notification_read_all_servlet.h"               // IWYU pragma: keep
#include "../servlets/notify/notification_read_servlet.h"                   // IWYU pragma: keep
#include "../servlets/notify/notification_send_servlet.h"                   // IWYU pragma: keep
#include "../servlets/notify/notification_unread_count_servlet.h"           // IWYU pragma: keep
#include "../servlets/notify/notify_servlet.h"                              // IWYU pragma: keep
#include "../servlets/organization/organization_admin_lists_servlet.h"      // IWYU pragma: keep
#include "../servlets/organization/organization_admin_stats_servlet.h"      // IWYU pragma: keep
#include "../servlets/organization/organization_assignment_list_servlet.h"  // IWYU pragma: keep
#include "../servlets/organization/organization_create_servlet.h"           // IWYU pragma: keep
#include "../servlets/organization/organization_delete_servlet.h"           // IWYU pragma: keep
#include "../servlets/organization/organization_detail_servlet.h"           // IWYU pragma: keep
#include "../servlets/organization/organization_join_check_servlet.h"       // IWYU pragma: keep
#include "../servlets/organization/organization_join_servlet.h"             // IWYU pragma: keep
#include "../servlets/organization/organization_list_servlet.h"             // IWYU pragma: keep
#include "../servlets/organization/organization_user_kick_servlet.h"        // IWYU pragma: keep
#include "../servlets/organization/organization_user_list_servlet.h"        // IWYU pragma: keep
#include "../servlets/organization/organization_user_switch_role_servlet.h" // IWYU pragma: keep
#include "../servlets/rd/rd_bug_delete_servlet.h"                           // IWYU pragma: keep
#include "../servlets/rd/rd_bug_detail_servlet.h"                           // IWYU pragma: keep
#include "../servlets/rd/rd_bug_edit_servlet.h"                             // IWYU pragma: keep
#include "../servlets/rd/rd_bug_servlet.h"                                  // IWYU pragma: keep
#include "../servlets/rd/rd_check_access_servlet.h"                         // IWYU pragma: keep
#include "../servlets/rd/rd_my_tickets_servlet.h"                           // IWYU pragma: keep
#include "../servlets/rd/rd_organization_members_servlet.h"                 // IWYU pragma: keep
#include "../servlets/rd/rd_organizations_servlet.h"                        // IWYU pragma: keep
#include "../servlets/rd/rd_requirement_delete_servlet.h"                   // IWYU pragma: keep
#include "../servlets/rd/rd_requirement_detail_servlet.h"                   // IWYU pragma: keep
#include "../servlets/rd/rd_requirement_edit_servlet.h"                     // IWYU pragma: keep
#include "../servlets/rd/rd_requirement_servlet.h"                          // IWYU pragma: keep
#include "../servlets/rd/rd_stats_servlet.h"                                // IWYU pragma: keep
#include "../servlets/rd/rd_task_delete_servlet.h"                          // IWYU pragma: keep
#include "../servlets/rd/rd_task_detail_servlet.h"                          // IWYU pragma: keep
#include "../servlets/rd/rd_task_edit_servlet.h"                            // IWYU pragma: keep
#include "../servlets/rd/rd_task_servlet.h"                                 // IWYU pragma: keep
#include "../servlets/settings/site_status_servlet.h"                       // IWYU pragma: keep
#include "../servlets/settings/system_settings_servlet.h"                   // IWYU pragma: keep
#include "../servlets/settings/system_settings_upload_servlet.h"            // IWYU pragma: keep
#include "../servlets/stats/stats_servlet.h"                                // IWYU pragma: keep
#include "../servlets/user/user_admin_create_servlet.h"                     // IWYU pragma: keep
#include "../servlets/user/user_admin_delete_servlet.h"                     // IWYU pragma: keep
#include "../servlets/user/user_admin_lists_servlet.h"                      // IWYU pragma: keep
#include "../servlets/user/user_admin_recover_servlet.h"                    // IWYU pragma: keep
#include "../servlets/user/user_admin_reset_passwd_servlet.h"               // IWYU pragma: keep
#include "../servlets/user/user_assignment_list_servlet.h"                  // IWYU pragma: keep
#include "../servlets/user/user_create_servlet.h"                           // IWYU pragma: keep
#include "../servlets/user/user_exists_servlet.h"                           // IWYU pragma: keep
#include "../servlets/user/user_follow_servlet.h"                           // IWYU pragma: keep
#include "../servlets/user/user_follower_list_servlet.h"                    // IWYU pragma: keep
#include "../servlets/user/user_following_list_servlet.h"                   // IWYU pragma: keep
#include "../servlets/user/user_info_servlet.h"                             // IWYU pragma: keep
#include "../servlets/user/user_is_following_servlet.h"                     // IWYU pragma: keep
#include "../servlets/user/user_list_servlet.h"                             // IWYU pragma: keep
#include "../servlets/user/user_login_servlet.h"                            // IWYU pragma: keep
#include "../servlets/user/user_logout_servlet.h"                           // IWYU pragma: keep
#include "../servlets/user/user_organization_list_servlet.h"                // IWYU pragma: keep
#include "../servlets/user/user_query_servlet.h"                            // IWYU pragma: keep
#include "../servlets/user/user_reset_passwd_servlet.h"                     // IWYU pragma: keep
#include "../servlets/user/user_send_code_servlet.h"                        // IWYU pragma: keep
#include "../servlets/user/user_stats_servlet.h"                            // IWYU pragma: keep
#include "../servlets/user/user_unfollow_servlet.h"                         // IWYU pragma: keep
#include "../servlets/user/user_update_servlet.h"                           // IWYU pragma: keep
