#include "../servlets/article/article_admin_lists_servlet.h"                // IWYU pragma: keep
#include "../servlets/article/article_admin_stats_servlet.h"                // IWYU pragma: keep
#include "../servlets/article/article_create_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/article_delete_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/article_detail_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/article_list_by_category_servlet.h"           // IWYU pragma: keep
#include "../servlets/article/article_list_by_label_servlet.h"              // IWYU pragma: keep
#include "../servlets/article/article_publish_servlet.h"                    // IWYU pragma: keep
#include "../servlets/article/article_query_servlet.h"                      // IWYU pragma: keep
#include "../servlets/article/article_switch_state_servlet.h"               // IWYU pragma: keep
#include "../servlets/article/article_update_category_servlet.h"            // IWYU pragma: keep
#include "../servlets/article/article_update_servlet.h"                     // IWYU pragma: keep
#include "../servlets/article/article_verify_servlet.h"                     // IWYU pragma: keep
#include "../servlets/assignment/assignment_admin_lists_servlet.h"          // IWYU pragma: keep
#include "../servlets/assignment/assignment_admin_stats_servlet.h"          // IWYU pragma: keep
#include "../servlets/assignment/assignment_create_servlet.h"               // IWYU pragma: keep
#include "../servlets/assignment/assignment_delete_servlet.h"               // IWYU pragma: keep
#include "../servlets/assignment/assignment_detail_servlet.h"               // IWYU pragma: keep
#include "../servlets/assignment/assignment_organization_create_servlet.h"  // IWYU pragma: keep
#include "../servlets/assignment/assignment_submission_list_servlet.h"      // IWYU pragma: keep
#include "../servlets/category/category_create_servlet.h"                   // IWYU pragma: keep
#include "../servlets/category/category_delete_servlet.h"                   // IWYU pragma: keep
#include "../servlets/category/category_query_servlet.h"                    // IWYU pragma: keep
#include "../servlets/file/chunk_upload_servlet.h"                          // IWYU pragma: keep
#include "../servlets/file/file_download_servlet.h"                         // IWYU pragma: keep
#include "../servlets/file/file_upload_servlet.h"                           // IWYU pragma: keep
#include "../servlets/label/label_create_servlet.h"                         // IWYU pragma: keep
#include "../servlets/label/label_delete_servlet.h"                         // IWYU pragma: keep
#include "../servlets/label/label_query_servlet.h"                          // IWYU pragma: keep
#include "../servlets/notify/notification_list_servlet.h"                   // IWYU pragma: keep
#include "../servlets/notify/notification_read_servlet.h"                   // IWYU pragma: keep
#include "../servlets/notify/notification_send_servlet.h"                   // IWYU pragma: keep
#include "../servlets/notify/notification_unread_count_servlet.h"           // IWYU pragma: keep
#include "../servlets/notify/notify_servlet.h"                              // IWYU pragma: keep
#include "../servlets/organization/organization_admin_lists_servlet.h"      // IWYU pragma: keep
#include "../servlets/organization/organization_admin_stats_servlet.h"      // IWYU pragma: keep
#include "../servlets/organization/organization_assignment_list_servlet.h"  // IWYU pragma: keep
#include "../servlets/organization/organization_create_servlet.h"           // IWYU pragma: keep
#include "../servlets/organization/organization_delete_servlet.h"           // IWYU pragma: keep
#include "../servlets/organization/organization_detail_servlet.h"           // IWYU pragma: keep
#include "../servlets/organization/organization_join_check_servlet.h"       // IWYU pragma: keep
#include "../servlets/organization/organization_join_servlet.h"             // IWYU pragma: keep
#include "../servlets/organization/organization_list_servlet.h"             // IWYU pragma: keep
#include "../servlets/organization/organization_user_kick_servlet.h"        // IWYU pragma: keep
#include "../servlets/organization/organization_user_list_servlet.h"        // IWYU pragma: keep
#include "../servlets/organization/organization_user_switch_role_servlet.h" // IWYU pragma: keep
#include "../servlets/user/user_admin_create_servlet.h"                     // IWYU pragma: keep
#include "../servlets/user/user_admin_delete_servlet.h"                     // IWYU pragma: keep
#include "../servlets/user/user_admin_lists_servlet.h"                      // IWYU pragma: keep
#include "../servlets/user/user_admin_recover_servlet.h"                    // IWYU pragma: keep
#include "../servlets/user/user_admin_reset_passwd_servlet.h"               // IWYU pragma: keep
#include "../servlets/user/user_assignment_list_servlet.h"                  // IWYU pragma: keep
#include "../servlets/user/user_create_servlet.h"                           // IWYU pragma: keep
#include "../servlets/user/user_exists_servlet.h"                           // IWYU pragma: keep
#include "../servlets/user/user_info_servlet.h"                             // IWYU pragma: keep
#include "../servlets/user/user_list_servlet.h"                             // IWYU pragma: keep
#include "../servlets/user/user_login_servlet.h"                            // IWYU pragma: keep
#include "../servlets/user/user_logout_servlet.h"                           // IWYU pragma: keep
#include "../servlets/user/user_organization_list_servlet.h"                // IWYU pragma: keep
#include "../servlets/user/user_query_servlet.h"                            // IWYU pragma: keep
#include "../servlets/user/user_reset_passwd_servlet.h"                     // IWYU pragma: keep
#include "../servlets/user/user_send_code_servlet.h"                        // IWYU pragma: keep
#include "../servlets/user/user_stats_servlet.h"                            // IWYU pragma: keep
#include "../servlets/user/user_update_servlet.h"                           // IWYU pragma: keep